# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Track Controller Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, QTime, Qt, QDateTime
import tkinter as tk
from tkinter import filedialog
from TestCases import Ui_AnotherWindow
import waysideController

class Ui_MainWindow(object):
    waysideControllers = [[waysideController]*26]*2
    blockOccupancies = [1,1,1,0]
    faultStatuses = [0,0,1,0]
    blockAuthorities = [1,0,0,1]
    underground = [0,1,1,0]
    outputs = [1,1,0,1]

    def openWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_AnotherWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    PLCFile=""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("SW Track Controller")
        MainWindow.resize(747, 643)
        MainWindow.setStyleSheet("background:rgb(230, 230, 230)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 731, 351))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("background-color: rgb(233, 245, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 181, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(320, 40, 391, 251))
        self.frame.setStyleSheet("image: url(C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/UX//Bachmann_G-scale_Track_Plan_1-640.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_4.setGeometry(QtCore.QRect(260, 50, 21, 21))
        self.textBrowser_4.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_3.setGeometry(QtCore.QRect(100, 70, 21, 21))
        self.textBrowser_3.setStyleSheet("\n"
"background-color: rgb(255, 0, 0);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(120, 170, 21, 21))
        self.textBrowser_2.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_5.setGeometry(QtCore.QRect(260, 170, 21, 21))
        self.textBrowser_5.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 181, 31))
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 181, 31))
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(30, 260, 181, 31))
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_2 = QtWidgets.QFrame(self.tab_5)
        self.frame_2.setGeometry(QtCore.QRect(320, 40, 391, 251))
        self.frame_2.setStyleSheet("image: url(C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/UX//Bachmann_G-scale_Track_Plan_1-640.jpg);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_6.setGeometry(QtCore.QRect(170, 50, 31, 21))
        self.textBrowser_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_7.setGeometry(QtCore.QRect(180, 180, 31, 21))
        self.textBrowser_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label_11.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(40, 70, 181, 31))
        self.label_12.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(40, 100, 181, 31))
        self.label_13.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(40, 130, 181, 31))
        self.label_14.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(40, 180, 181, 31))
        self.label_16.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(40, 210, 181, 31))
        self.label_17.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(40, 240, 181, 31))
        self.label_18.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_20.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(180,140,61,16))
        self.label_22.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(180,250,61,16))
        self.label_23.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(40,280,181,31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(320, 40, 391, 251))
        self.frame_3.setStyleSheet("image: url(C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/UX//Bachmann_G-scale_Track_Plan_1-640.jpg);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_9.setGeometry(QtCore.QRect(360, 120, 31, 21))
        self.textBrowser_9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_8.setGeometry(QtCore.QRect(0, 120, 31, 21))
        self.textBrowser_8.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(30, 70, 181, 31))
        self.label_26.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(30, 10, 141, 31))
        self.label_30.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(30, 170, 181, 31))
        self.label_27.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(30, 100, 181, 31))
        self.label_28.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_29.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(30, 130, 181, 31))
        self.label_31.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_32.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(30, 200, 181, 31))
        self.label_33.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(30, 230, 181, 31))
        self.label_34.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_35.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_36.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(320, 40, 391, 251))
        self.frame_6.setStyleSheet("image: url(C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/UX//Bachmann_G-scale_Track_Plan_1-640.jpg);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_16.setGeometry(QtCore.QRect(340, 70, 21, 21))
        self.textBrowser_16.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_17.setGeometry(QtCore.QRect(30, 170, 21, 21))
        self.textBrowser_17.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.label_68 = QtWidgets.QLabel(self.tab_2)
        self.label_68.setGeometry(QtCore.QRect(40, 110, 211, 31))
        self.label_68.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.tab_2)
        self.label_69.setGeometry(QtCore.QRect(40, 60, 211, 51))
        self.label_69.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.tab_2)
        self.label_70.setGeometry(QtCore.QRect(40, 180, 181, 31))
        self.label_70.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.tab_2)
        self.label_71.setGeometry(QtCore.QRect(40, 140, 211, 31))
        self.label_71.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.tab_2)
        self.label_72.setGeometry(QtCore.QRect(40, 240, 181, 31))
        self.label_72.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.tab_2)
        self.label_73.setGeometry(QtCore.QRect(40, 210, 181, 31))
        self.label_73.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_2)
        self.label_74.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_74.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab_2)
        self.label_75.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_75.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.tab_2)
        self.label_76.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_76.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.tab_2)
        self.label_77.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_77.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_2)
        self.label_78.setGeometry(QtCore.QRect(40, 20, 141, 31))
        self.label_78.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_78.setObjectName("label_78")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.frame_4 = QtWidgets.QFrame(self.tab_6)
        self.frame_4.setGeometry(QtCore.QRect(320, 40, 391, 251))
        self.frame_4.setStyleSheet("image: url(C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/UX//Bachmann_G-scale_Track_Plan_1-640.jpg);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_11.setGeometry(QtCore.QRect(0, 130, 31, 21))
        self.textBrowser_11.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_10.setGeometry(QtCore.QRect(360, 120, 31, 21))
        self.textBrowser_10.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_12.setGeometry(QtCore.QRect(110, 40, 31, 21))
        self.textBrowser_12.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_13.setGeometry(QtCore.QRect(170, 60, 31, 21))
        self.textBrowser_13.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_14.setGeometry(QtCore.QRect(230, 90, 31, 21))
        self.textBrowser_14.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_15.setGeometry(QtCore.QRect(180, 180, 31, 21))
        self.textBrowser_15.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(40, 20, 161, 31))
        self.label_37.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setGeometry(QtCore.QRect(10, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setGeometry(QtCore.QRect(10, 90, 121, 21))
        self.label_39.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setGeometry(QtCore.QRect(10, 110, 121, 31))
        self.label_40.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_6)
        self.label_41.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_41.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_6)
        self.label_42.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_42.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setGeometry(QtCore.QRect(10, 170, 121, 21))
        self.label_43.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setGeometry(QtCore.QRect(10, 190, 121, 31))
        self.label_44.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_6)
        self.label_45.setGeometry(QtCore.QRect(10, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.tab_6)
        self.label_46.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_46.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_6)
        self.label_47.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_47.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_6)
        self.label_48.setGeometry(QtCore.QRect(10, 250, 121, 21))
        self.label_48.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setGeometry(QtCore.QRect(10, 270, 121, 31))
        self.label_49.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_6)
        self.label_50.setGeometry(QtCore.QRect(10, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_6)
        self.label_51.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_51.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_6)
        self.label_52.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_52.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_6)
        self.label_53.setGeometry(QtCore.QRect(160, 90, 121, 21))
        self.label_53.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_6)
        self.label_54.setGeometry(QtCore.QRect(160, 110, 121, 31))
        self.label_54.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_6)
        self.label_55.setGeometry(QtCore.QRect(160, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_6)
        self.label_56.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_56.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_57.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.tab_6)
        self.label_58.setGeometry(QtCore.QRect(160, 170, 121, 21))
        self.label_58.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_6)
        self.label_59.setGeometry(QtCore.QRect(160, 190, 121, 31))
        self.label_59.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_6)
        self.label_60.setGeometry(QtCore.QRect(160, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_6)
        self.label_61.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_61.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_6)
        self.label_62.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_62.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_6)
        self.label_63.setGeometry(QtCore.QRect(160, 250, 121, 21))
        self.label_63.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_6)
        self.label_64.setGeometry(QtCore.QRect(160, 270, 121, 31))
        self.label_64.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_6)
        self.label_65.setGeometry(QtCore.QRect(160, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_6)
        self.label_66.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_66.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.tab_6)
        self.label_67.setGeometry(QtCore.QRect(0,0,0,0))
        self.label_67.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);")
        self.label_67.setObjectName("label_67")
        self.tabWidget.addTab(self.tab_6, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 151, 81))
        self.textBrowser.setStyleSheet("background-color: rgb(233, 245, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 500, 641, 31))
        self.textEdit.setObjectName("textEdit")
        self.runButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(660, 500, 71, 31))
        self.runButton.setStyleSheet("background-color: rgb(233, 245, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.runButton.setObjectName("runButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 480, 101, 16))
        self.label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.loadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFileButton.setGeometry(QtCore.QRect(10, 540, 141, 23))
        self.loadFileButton.setObjectName("loadFileButton")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_79.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 0);")
        self.label_79.setObjectName("label_79")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(580, 10, 151, 31))
        self.logoutButton.setObjectName("logoutButton")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 751, 601))
        self.frame_7.setStyleSheet("background:rgb(211, 211, 211)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_7.raise_()
        self.tabWidget.raise_()
        self.textBrowser.raise_()
        self.textEdit.raise_()
        self.runButton.raise_()
        self.label.raise_()
        self.loadFileButton.raise_()
        self.label_79.raise_()
        self.logoutButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Switch 1 - (North End 1):"))
        self.label_3.setText(_translate("MainWindow", "Switch Status:"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">S1</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">S2</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">S3</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">S4</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Switch 2 - (North End 2):"))
        self.label_5.setText(_translate("MainWindow", "Switch 3 - (South End 1):"))
        self.label_6.setText(_translate("MainWindow", "OPEN"))
        self.label_7.setText(_translate("MainWindow", "OPEN"))
        self.label_8.setText(_translate("MainWindow", "CLOSED"))
        self.label_9.setText(_translate("MainWindow", "Switch 4 - (South End 2):"))
        self.label_10.setText(_translate("MainWindow", "OPEN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Track Switches"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">ST1</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">ST2</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Station Status:"))
        self.label_12.setText(_translate("MainWindow", "Station 1 - (North End):"))
        self.label_13.setText(_translate("MainWindow", "Train Present:"))
        self.label_14.setText(_translate("MainWindow", "North End Speed Limit:"))
        self.label_16.setText(_translate("MainWindow", "Station 2 - (South End):"))
        self.label_17.setText(_translate("MainWindow", "Train Present:"))
        self.label_18.setText(_translate("MainWindow", "South End Speed Limit:"))
        self.label_20.setText(_translate("MainWindow", "NO"))
        self.label_21.setText(_translate("MainWindow", "YES"))
        self.label_22.setText(_translate("MainWindow", ""))
        self.label_23.setText(_translate("MainWindow", ""))
        self.label_19.setText(_translate("MainWindow", "Set Authority:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Stations"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">CR2</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">CR1</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "Crossing 1 - (West):"))
        self.label_30.setText(_translate("MainWindow", "Crossing Status:"))
        self.label_27.setText(_translate("MainWindow", "Crossing 2 - (East):"))
        self.label_28.setText(_translate("MainWindow", "Train Present:"))
        self.label_29.setText(_translate("MainWindow", "NO"))
        self.label_31.setText(_translate("MainWindow", "Crossing Status: "))
        self.label_32.setText(_translate("MainWindow", "OPEN"))
        self.label_33.setText(_translate("MainWindow", "Train Present:"))
        self.label_34.setText(_translate("MainWindow", "Crossing Status: "))
        self.label_35.setText(_translate("MainWindow", "CLOSED"))
        self.label_36.setText(_translate("MainWindow", "YES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Crossings"))
        self.textBrowser_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">L1</span></p></body></html>"))
        self.textBrowser_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">L2</span></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "Train Present:"))
        self.label_69.setText(_translate("MainWindow", "Light 1 - (Northeast)"))
        self.label_70.setText(_translate("MainWindow", "Light 2 - (Southwest)"))
        self.label_71.setText(_translate("MainWindow", "Light Status:"))
        self.label_72.setText(_translate("MainWindow", "Light Status: "))
        self.label_73.setText(_translate("MainWindow", "Train Present:"))
        self.label_74.setText(_translate("MainWindow", "NO"))
        self.label_75.setText(_translate("MainWindow", "RED"))
        self.label_76.setText(_translate("MainWindow", "NO"))
        self.label_77.setText(_translate("MainWindow", "Green"))
        self.label_78.setText(_translate("MainWindow", "Light Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Lights"))
        self.textBrowser_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">FA1</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">FA6</span></p></body></html>"))
        self.textBrowser_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">FA2</span></p></body></html>"))
        self.textBrowser_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">FA3</span></p></body></html>"))
        self.textBrowser_14.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">FA4</span></p></body></html>"))
        self.textBrowser_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">FA5</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "Track Fault Status:"))
        self.label_38.setText(_translate("MainWindow", "Fault Area 1 (West)"))
        self.label_39.setText(_translate("MainWindow", "Fault:"))
        self.label_40.setText(_translate("MainWindow", "Fault Type:"))
        self.label_41.setText(_translate("MainWindow", "NO"))
        self.label_42.setText(_translate("MainWindow", "N/A"))
        self.label_43.setText(_translate("MainWindow", "Fault:"))
        self.label_44.setText(_translate("MainWindow", "Fault Type:"))
        self.label_45.setText(_translate("MainWindow", "Fault Area 2 (North 1)"))
        self.label_46.setText(_translate("MainWindow", "N/A"))
        self.label_47.setText(_translate("MainWindow", "NO"))
        self.label_48.setText(_translate("MainWindow", "Fault:"))
        self.label_49.setText(_translate("MainWindow", "Fault Type:"))
        self.label_50.setText(_translate("MainWindow", "Fault Area 3 (North 2)"))
        self.label_51.setText(_translate("MainWindow", "N/A"))
        self.label_52.setText(_translate("MainWindow", "NO"))
        self.label_53.setText(_translate("MainWindow", "Fault:"))
        self.label_54.setText(_translate("MainWindow", "Fault Type:"))
        self.label_55.setText(_translate("MainWindow", "Fault Area 4 (North 3)"))
        self.label_56.setText(_translate("MainWindow", "N/A"))
        self.label_57.setText(_translate("MainWindow", "NO"))
        self.label_58.setText(_translate("MainWindow", "Fault:"))
        self.label_59.setText(_translate("MainWindow", "Fault Type:"))
        self.label_60.setText(_translate("MainWindow", "Fault Area 5 (South)"))
        self.label_61.setText(_translate("MainWindow", "N/A"))
        self.label_62.setText(_translate("MainWindow", "NO"))
        self.label_63.setText(_translate("MainWindow", "Fault:"))
        self.label_64.setText(_translate("MainWindow", "Fault Type:"))
        self.label_65.setText(_translate("MainWindow", "Fault Area 6 (East)"))
        self.label_66.setText(_translate("MainWindow", "Rail Break"))
        self.label_67.setText(_translate("MainWindow", "YES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Fault Status"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">2/9/2021 - 10:34 AM</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">diagnosticFunction(Switches)</span></p></body></html>"))
        self.runButton.setText(_translate("MainWindow", "RUN"))
        self.label.setText(_translate("MainWindow", "CMD"))
        self.loadFileButton.setText(_translate("MainWindow", "Load File"))
        self.label_79.setText(_translate("MainWindow", ""))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.realTime()
        
        
        
    def realTime(self):
        print("Load Your Initial PLC File:")
        root=tk.Tk()
        root.withdraw()
        file_path = filedialog.askopenfilename()
        self.PLCFile=file_path
        if file_path.partition(".")[2] != "py":
              print("ERROR! Incorrect/Invalid PLC File")
              sys.exit()          
        self.logoutButton.clicked.connect(self.clickedLogout)
        self.loadFileButton.clicked.connect(self.clickedLF)
        self.runButton.clicked.connect(self.clickedCommand)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.UpdatePLC)
        self.timer.start(1000)
        
        
    def clickedLogout(self):
        sys.exit()

    def clickedCommand(self):
        if self.textEdit.toPlainText() == "diagnosticFunction()":
                self.openWindow()
        else:
                print("Command Run Failed: Unknown Function")


    def clickedLF(self):
        root=tk.Tk()
        root.withdraw()
        file_path = filedialog.askopenfilename()
        _translate = QtCore.QCoreApplication.translate
        if file_path.partition(".")[2] != "py":
                self.label_79.setText(_translate("MainWindow", "File Load Failed")) 
                self.label_79.setGeometry(QtCore.QRect(160, 540, 151, 16))
                self.label_79.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                QtCore.QTimer.singleShot(3000, self.checkFailPassLabel)
        else:
                self.label_79.setText(_translate("MainWindow", "File Load Successful")) 
                self.label_79.setGeometry(QtCore.QRect(160, 540, 151, 16))
                self.label_79.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.PLCFile=file_path
                QtCore.QTimer.singleShot(3000, self.checkFailPassLabel)
                
                
    def checkFailPassLabel(self):
            _translate = QtCore.QCoreApplication.translate
            self.label_79.setText(_translate("MainWindow", "")) 
            self.label_79.setGeometry(QtCore.QRect(0, 0, 0, 0))
            
    def UpdatePLC(self):
            _translate = QtCore.QCoreApplication.translate
            exec(open(self.PLCFile).read())
            with open('ControllerSignals.txt','r') as file:
                Content=file.readlines()
            SW1Pos=bool(int(str(Content[1])[-2]))
            SW2Pos=bool(int(str(Content[3])[-2]))
            SW3Pos=bool(int(str(Content[5])[-2]))
            SW4Pos=bool(int(str(Content[7])[-2]))
            Light1Occ=bool(int(str(Content[8])[-2]))
            ST1Occ=bool(int(str(Content[10])[-2]))
            Light2Occ=bool(int(str(Content[11])[-2]))
            ST2Occ=bool(int(str(Content[13])[-2]))
            Cross1Occ=bool(int(str(Content[14])[-2]))
            Cross2Occ=bool(int(str(Content[15])[-2]))
            AuthChangeReq=bool(int(str(Content[16])[-2]))
            L1Out=bool(int(str(Content[21])[-2]))
            L2Out=bool(int(str(Content[22])[-2]))
            Cross1Out=bool(int(str(Content[23])[-2]))
            Cross2Out=bool(int(str(Content[24])[-2]))
            NESpeed=str(''.join(filter(lambda i: i.isdigit(), Content[27])))
            SESpeed=str(''.join(filter(lambda i: i.isdigit(), Content[28])))
            Auth=str(''.join(filter(lambda i: i.isdigit(), Content[29])))
            FA1=bool(int(str(Content[30])[-2]))
            FA2=bool(int(str(Content[32])[-2]))
            FA3=bool(int(str(Content[34])[-2]))
            FA4=bool(int(str(Content[36])[-2]))
            FA5=bool(int(str(Content[38])[-2]))
            FA6=bool(int(str(Content[40])[-2]))
            FA1Type=str(Content[31]).split('=',1)[1]
            FA2Type=str(Content[33]).split('=',1)[1]
            FA3Type=str(Content[35]).split('=',1)[1]
            FA4Type=str(Content[37]).split('=',1)[1]
            FA5Type=str(Content[39]).split('=',1)[1]
            FA6Type=str(Content[41]).split('=',1)[1]

            

            
            if SW1Pos == True:
                self.label_6.setText(_translate("MainWindow", "OPEN")) 
                self.label_6.setGeometry(QtCore.QRect(220, 60, 47, 19))
                self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_6.setText(_translate("MainWindow", "CLOSED")) 
                self.label_6.setGeometry(QtCore.QRect(220, 60, 61, 16))
                self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if SW2Pos == True:
                self.label_8.setText(_translate("MainWindow", "OPEN")) 
                self.label_8.setGeometry(QtCore.QRect(220, 130, 47, 19))
                self.label_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_8.setText(_translate("MainWindow", "CLOSED")) 
                self.label_8.setGeometry(QtCore.QRect(220, 130, 61, 16))
                self.label_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if SW3Pos == True:
                self.label_7.setText(_translate("MainWindow", "OPEN")) 
                self.label_7.setGeometry(QtCore.QRect(220, 200, 47, 19))
                self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_7.setText(_translate("MainWindow", "CLOSED")) 
                self.label_7.setGeometry(QtCore.QRect(220, 200, 61, 16))
                self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if SW4Pos == True:
                self.label_10.setText(_translate("MainWindow", "OPEN")) 
                self.label_10.setGeometry(QtCore.QRect(220, 270, 47, 19))
                self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_10.setText(_translate("MainWindow", "CLOSED")) 
                self.label_10.setGeometry(QtCore.QRect(220, 270, 61, 16))
                self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")

            if Cross1Occ == True:
                self.label_29.setText(_translate("MainWindow", "YES")) 
                self.label_29.setGeometry(QtCore.QRect(120, 110, 31, 16))
                self.label_29.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_29.setText(_translate("MainWindow", "NO")) 
                self.label_29.setGeometry(QtCore.QRect(120, 110, 31, 16))
                self.label_29.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if Cross2Occ == True:
                self.label_36.setText(_translate("MainWindow", "YES")) 
                self.label_36.setGeometry(QtCore.QRect(120, 210, 31, 16))
                self.label_36.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_36.setText(_translate("MainWindow", "NO")) 
                self.label_36.setGeometry(QtCore.QRect(120, 210, 31, 16))
                self.label_36.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if Cross1Out == False:
                self.label_32.setText(_translate("MainWindow", "OPEN")) 
                self.label_32.setGeometry(QtCore.QRect(130, 140, 47, 13))
                self.label_32.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_32.setText(_translate("MainWindow", "CLOSED")) 
                self.label_32.setGeometry(QtCore.QRect(130, 140, 61, 16))
                self.label_32.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if Cross2Out == False:
                self.label_35.setText(_translate("MainWindow", "OPEN")) 
                self.label_35.setGeometry(QtCore.QRect(130, 240, 47, 13))
                self.label_35.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_35.setText(_translate("MainWindow", "CLOSED")) 
                self.label_35.setGeometry(QtCore.QRect(130, 240, 61, 16))
                self.label_35.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")

            if Light1Occ == True:
                self.label_74.setText(_translate("MainWindow", "YES")) 
                self.label_74.setGeometry(QtCore.QRect(130, 120, 31, 16))
                self.label_74.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_74.setText(_translate("MainWindow", "NO")) 
                self.label_74.setGeometry(QtCore.QRect(130, 120, 31, 16))
                self.label_74.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if Light2Occ == True:
                self.label_76.setText(_translate("MainWindow", "YES")) 
                self.label_76.setGeometry(QtCore.QRect(130, 220, 31, 16))
                self.label_76.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_76.setText(_translate("MainWindow", "NO")) 
                self.label_76.setGeometry(QtCore.QRect(130, 220, 31, 16))
                self.label_76.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if L1Out == False:
                self.label_75.setText(_translate("MainWindow", "GREEN")) 
                self.label_75.setGeometry(QtCore.QRect(120, 150, 51, 16))
                self.label_75.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_75.setText(_translate("MainWindow", "RED")) 
                self.label_75.setGeometry(QtCore.QRect(120, 150, 31, 16))
                self.label_75.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if L2Out == False:
                self.label_77.setText(_translate("MainWindow", "GREEN")) 
                self.label_77.setGeometry(QtCore.QRect(120, 250, 51, 16))
                self.label_77.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_17.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_77.setText(_translate("MainWindow", "RED")) 
                self.label_77.setGeometry(QtCore.QRect(120, 250, 31, 16))
                self.label_77.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_17.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")

            if ST1Occ == True:
                self.label_20.setText(_translate("MainWindow", "YES")) 
                self.label_20.setGeometry(QtCore.QRect(130, 110, 31, 16))
                self.label_20.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_20.setText(_translate("MainWindow", "NO")) 
                self.label_20.setGeometry(QtCore.QRect(130, 110, 31, 16))
                self.label_20.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            if ST2Occ == True:
                self.label_21.setText(_translate("MainWindow", "YES")) 
                self.label_21.setGeometry(QtCore.QRect(130, 220, 31, 16))
                self.label_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
            else:
                self.label_21.setText(_translate("MainWindow", "NO")) 
                self.label_21.setGeometry(QtCore.QRect(130, 220, 31, 16))
                self.label_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
            
            self.label_22.setText(_translate("MainWindow", NESpeed+"MPH")) 
            self.label_23.setText(_translate("MainWindow", SESpeed+"MPH")) 

            if AuthChangeReq == 1 and "Set Authority: "+Auth+" mi." != self.label_19.text():
                self.label_19.setText(_translate("MainWindow", "Set Authority: "+Auth+" mi."))

                     
            if FA1 == 0:
                self.label_41.setText(_translate("MainWindow", "NO")) 
                self.label_41.setGeometry(QtCore.QRect(40, 90, 31, 16))
                self.label_41.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.label_42.setText(_translate("MainWindow", "N/A")) 
                self.label_42.setGeometry(QtCore.QRect(70, 110, 31, 31))
            else:
                self.label_41.setText(_translate("MainWindow", "YES")) 
                self.label_41.setGeometry(QtCore.QRect(40, 90, 31, 16))
                self.label_41.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.label_42.setText(_translate("MainWindow", FA1Type))
                self.label_42.setGeometry(QtCore.QRect(70, 110, 104, 41))
            if FA2 == 0:
                self.label_47.setText(_translate("MainWindow", "NO")) 
                self.label_47.setGeometry(QtCore.QRect(40, 170, 31, 16))
                self.label_47.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.label_46.setText(_translate("MainWindow", "N/A")) 
                self.label_46.setGeometry(QtCore.QRect(70, 190, 31, 31))
            else:
                self.label_47.setText(_translate("MainWindow", "YES")) 
                self.label_47.setGeometry(QtCore.QRect(40, 170, 31, 16))
                self.label_47.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.label_46.setText(_translate("MainWindow", FA2Type))
                self.label_46.setGeometry(QtCore.QRect(70, 190, 104, 41))
            if FA3 == 0:
                self.label_52.setText(_translate("MainWindow", "NO")) 
                self.label_52.setGeometry(QtCore.QRect(40, 250, 31, 16))
                self.label_52.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.label_51.setText(_translate("MainWindow", "N/A")) 
                self.label_51.setGeometry(QtCore.QRect(70, 270, 31, 31))
            else:
                self.label_52.setText(_translate("MainWindow", "YES")) 
                self.label_52.setGeometry(QtCore.QRect(40, 250, 31, 16))
                self.label_52.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.label_51.setText(_translate("MainWindow", FA3Type)) 
                self.label_51.setGeometry(QtCore.QRect(65, 270, 104, 41))
            if FA4 == 0:
                self.label_57.setText(_translate("MainWindow", "NO")) 
                self.label_57.setGeometry(QtCore.QRect(190, 90, 31, 16))
                self.label_57.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.label_56.setText(_translate("MainWindow", "N/A"))
                self.label_56.setGeometry(QtCore.QRect(220, 110, 31, 31)) 
            else:
                self.label_57.setText(_translate("MainWindow", "YES")) 
                self.label_57.setGeometry(QtCore.QRect(190, 90, 31, 16))
                self.label_57.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.label_56.setText(_translate("MainWindow", FA4Type)) 
                self.label_56.setGeometry(QtCore.QRect(220, 110, 104, 41))
            if FA5 == 0:
                self.label_62.setText(_translate("MainWindow", "NO")) 
                self.label_62.setGeometry(QtCore.QRect(190, 170, 31, 16))
                self.label_62.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_15.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.label_61.setText(_translate("MainWindow", "N/A")) 
                self.label_61.setGeometry(QtCore.QRect(220, 190, 31, 31)) 
            else:
                self.label_62.setText(_translate("MainWindow", "YES")) 
                self.label_62.setGeometry(QtCore.QRect(190, 170, 31, 16))
                self.label_62.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_15.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.label_61.setText(_translate("MainWindow", FA5Type)) 
                self.label_61.setGeometry(QtCore.QRect(220, 190, 104, 41))
            if FA6 == 0:
                self.label_67.setText(_translate("MainWindow", "NO")) 
                self.label_67.setGeometry(QtCore.QRect(190, 250, 31, 16))
                self.label_67.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.textBrowser_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.label_66.setText(_translate("MainWindow", "N/A")) 
                self.label_66.setGeometry(QtCore.QRect(220, 270, 31, 31))
            else:
                self.label_67.setText(_translate("MainWindow", "YES")) 
                self.label_67.setGeometry(QtCore.QRect(190, 250, 31, 16))
                self.label_67.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.textBrowser_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")
                self.label_66.setText(_translate("MainWindow", FA6Type)) 
                self.label_66.setGeometry(QtCore.QRect(220, 270, 111, 41))

            self.textBrowser.setText(_translate("MainWindow", QDate.currentDate().toString(Qt.ISODate)+"\n"+QTime.currentTime().toString(Qt.DefaultLocaleLongDate)))
            self.textBrowser.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n""background-color: rgb(233, 245, 255);")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
