# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrackControllerHomeNew2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time
from PyQt5.QtCore import QDateTime, Qt, QTime, QDate
import tkinter as tk
from tkinter import filedialog
from TestCases import Ui_AnotherWindow
from waysideController import waysideController
import os
import trackModel
import t1_1
from t1_1 import CTCOFFICE
import sys
from tkinter import *

#CTC=CTCOFFICE(window)

class Ui_MainWindow(object):

    sugSpeed=0
    auth=0
    waysideControllers=[[]*2]*26
    redBlockNum=[]
    greenBlockNum=[]
    prevRoutedBlocks=[]
    prevRoutedLines=[]
    prevRoutedSections=[]
    routedBlockEqual=True
    
    def trackModelInput(self, obj):
        self.trackModelDatabase=obj

    def CTCInput(self,obj):
        self.CTC=obj
        
    def setupControllers(self):
        self.redStarts=[1,4,7,10,13,16,21,24,46,49,55,58,61,64,67,68,71,72,73,76]
        self.greenStarts=[1,4,7,13,17,21,29,33,36,58,63,69,74,77,86,89,98,101,102,105,110,117,122,144,147,150]

        for i in range(20):
            if i==19:
                self.waysideControllers[0].append(waysideController(i,"Red",self.redStarts[i],1))
            else:
                self.waysideControllers[0].append( waysideController(i, "Red",self.redStarts[i],self.redStarts[i+1]-self.redStarts[i] ))
            
        for i in range(26):
            if i==25:
                self.waysideControllers[1].append( waysideController(i, "Green",self.greenStarts[i], 1) )
            else:
                self.waysideControllers[1].append( waysideController(i, "Green",self.greenStarts[i], self.greenStarts[i+1]-self.greenStarts[i]) )

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1383, 963)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LineTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.LineTabWidget.setGeometry(QtCore.QRect(10, 10, 1351, 841))
        self.LineTabWidget.setStyleSheet("background:rgb(216, 245, 255)")
        self.LineTabWidget.setObjectName("LineTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.MainTabsRed = QtWidgets.QTabWidget(self.tab)
        self.MainTabsRed.setGeometry(QtCore.QRect(9, 9, 1291, 791))
        self.MainTabsRed.setObjectName("MainTabsRed")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.frame_6 = QtWidgets.QFrame(self.tab_8)
        self.frame_6.setGeometry(QtCore.QRect(600, 0, 686, 769))
        self.frame_6.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 661, 741))
        self.label_8.setObjectName("label_8")
        self.ShadysideLabel = QtWidgets.QLabel(self.frame_6)
        self.ShadysideLabel.setGeometry(QtCore.QRect(560, 120, 58, 16))
        self.ShadysideLabel.setObjectName("ShadysideLabel")
        self.HerronLabel = QtWidgets.QLabel(self.frame_6)
        self.HerronLabel.setGeometry(QtCore.QRect(360, 190, 64, 16))
        self.HerronLabel.setObjectName("HerronLabel")
        self.SwissvilleLabel = QtWidgets.QLabel(self.frame_6)
        self.SwissvilleLabel.setGeometry(QtCore.QRect(270, 210, 54, 16))
        self.SwissvilleLabel.setObjectName("SwissvilleLabel")
        self.PennStationLabel = QtWidgets.QLabel(self.frame_6)
        self.PennStationLabel.setGeometry(QtCore.QRect(300, 260, 72, 16))
        self.PennStationLabel.setObjectName("PennStationLabel")
        self.SteelPlazaLabel = QtWidgets.QLabel(self.frame_6)
        self.SteelPlazaLabel.setGeometry(QtCore.QRect(280, 370, 62, 16))
        self.SteelPlazaLabel.setObjectName("SteelPlazaLabel")
        self.FirstAveLabel = QtWidgets.QLabel(self.frame_6)
        self.FirstAveLabel.setGeometry(QtCore.QRect(290, 470, 50, 16))
        self.FirstAveLabel.setObjectName("FirstAveLabel")
        self.StationSquareLabel = QtWidgets.QLabel(self.frame_6)
        self.StationSquareLabel.setGeometry(QtCore.QRect(240, 570, 84, 16))
        self.StationSquareLabel.setObjectName("StationSquareLabel")
        self.SHJunctionLabel = QtWidgets.QLabel(self.frame_6)
        self.SHJunctionLabel.setGeometry(QtCore.QRect(40, 430, 66, 16))
        self.SHJunctionLabel.setObjectName("SHJunctionLabel")
        self.frame_3 = QtWidgets.QFrame(self.tab_8)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_3.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_8)
        self.frame_4.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_4.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_836 = QtWidgets.QLabel(self.frame_4)
        self.label_836.setGeometry(QtCore.QRect(20, 200, 241, 41))
        self.label_836.setObjectName("label_836")
        self.label_837 = QtWidgets.QLabel(self.frame_4)
        self.label_837.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_837.setObjectName("label_837")
        self.RedStationSelBox = QtWidgets.QComboBox(self.frame_4)
        self.RedStationSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.RedStationSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.RedStationSelBox.setObjectName("RedStationSelBox")
        self.RedStationOccLabel = QtWidgets.QLabel(self.frame_4)
        self.RedStationOccLabel.setGeometry(QtCore.QRect(190, 130, 251, 41))
        self.RedStationOccLabel.setObjectName("RedStationOccLabel")
        self.RedStationTixLabel = QtWidgets.QLabel(self.frame_4)
        self.RedStationTixLabel.setGeometry(QtCore.QRect(280, 200, 111, 41))
        self.RedStationTixLabel.setObjectName("RedStationTixLabel")
        self.label_838 = QtWidgets.QLabel(self.frame_4)
        self.label_838.setGeometry(QtCore.QRect(20, 130, 151, 41))
        self.label_838.setObjectName("label_838")
        self.frame_3.raise_()
        self.frame_6.raise_()
        self.frame_4.raise_()
        self.MainTabsRed.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.frame_7 = QtWidgets.QFrame(self.tab_9)
        self.frame_7.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_7.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_9.setObjectName("label_9")
        self.Yrd_CDLabel = QtWidgets.QLabel(self.frame_7)
        self.Yrd_CDLabel.setGeometry(QtCore.QRect(590, 170, 61, 21))
        self.Yrd_CDLabel.setObjectName("Yrd_CDLabel")
        self.F_AELabel = QtWidgets.QLabel(self.frame_7)
        self.F_AELabel.setGeometry(QtCore.QRect(390, 190, 71, 21))
        self.F_AELabel.setObjectName("F_AELabel")
        self.T_HLabel = QtWidgets.QLabel(self.frame_7)
        self.T_HLabel.setGeometry(QtCore.QRect(290, 270, 81, 21))
        self.T_HLabel.setObjectName("T_HLabel")
        self.R_HLabel = QtWidgets.QLabel(self.frame_7)
        self.R_HLabel.setGeometry(QtCore.QRect(290, 350, 81, 21))
        self.R_HLabel.setObjectName("R_HLabel")
        self.Q_HLabel = QtWidgets.QLabel(self.frame_7)
        self.Q_HLabel.setGeometry(QtCore.QRect(290, 410, 81, 21))
        self.Q_HLabel.setObjectName("Q_HLabel")
        self.O_HLabel = QtWidgets.QLabel(self.frame_7)
        self.O_HLabel.setGeometry(QtCore.QRect(290, 480, 81, 21))
        self.O_HLabel.setObjectName("O_HLabel")
        self.I_JNLabel = QtWidgets.QLabel(self.frame_7)
        self.I_JNLabel.setGeometry(QtCore.QRect(160, 560, 81, 21))
        self.I_JNLabel.setObjectName("I_JNLabel")
        self.frame = QtWidgets.QFrame(self.tab_9)
        self.frame.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.RedSwitchSelBox = QtWidgets.QComboBox(self.frame)
        self.RedSwitchSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.RedSwitchSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.RedSwitchSelBox.setObjectName("RedSwitchSelBox")
        self.label_831 = QtWidgets.QLabel(self.frame)
        self.label_831.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_831.setObjectName("label_831")
        self.RedSwitchPosLabel = QtWidgets.QLabel(self.frame)
        self.RedSwitchPosLabel.setGeometry(QtCore.QRect(240, 130, 111, 41))
        self.RedSwitchPosLabel.setObjectName("RedSwitchPosLabel")
        self.label_833 = QtWidgets.QLabel(self.frame)
        self.label_833.setGeometry(QtCore.QRect(20, 130, 211, 41))
        self.label_833.setObjectName("label_833")
        self.RedSwitchDirLabel = QtWidgets.QLabel(self.frame)
        self.RedSwitchDirLabel.setGeometry(QtCore.QRect(160, 200, 111, 41))
        self.RedSwitchDirLabel.setObjectName("RedSwitchDirLabel")
        self.label_835 = QtWidgets.QLabel(self.frame)
        self.label_835.setGeometry(QtCore.QRect(20, 200, 121, 41))
        self.label_835.setObjectName("label_835")
        self.frame_2 = QtWidgets.QFrame(self.tab_9)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_2.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.frame.raise_()
        self.frame_7.raise_()
        self.MainTabsRed.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.frame_9 = QtWidgets.QFrame(self.tab_10)
        self.frame_9.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_9.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_11.setObjectName("label_11")
        self.frame_22 = QtWidgets.QFrame(self.tab_10)
        self.frame_22.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_22.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.frame_23 = QtWidgets.QFrame(self.tab_10)
        self.frame_23.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_23.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_830 = QtWidgets.QLabel(self.frame_23)
        self.label_830.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_830.setObjectName("label_830")
        self.label_846 = QtWidgets.QLabel(self.frame_23)
        self.label_846.setGeometry(QtCore.QRect(280, 20, 231, 41))
        self.label_846.setObjectName("label_846")
        self.RedLightOccLabel = QtWidgets.QLabel(self.frame_23)
        self.RedLightOccLabel.setGeometry(QtCore.QRect(190, 130, 111, 41))
        self.RedLightOccLabel.setObjectName("RedLightOccLabel")
        self.label_832 = QtWidgets.QLabel(self.frame_23)
        self.label_832.setGeometry(QtCore.QRect(20, 200, 171, 41))
        self.label_832.setObjectName("label_832")
        self.RedLightStatLabel = QtWidgets.QLabel(self.frame_23)
        self.RedLightStatLabel.setGeometry(QtCore.QRect(200, 200, 111, 41))
        self.RedLightStatLabel.setObjectName("RedLightStatLabel")
        self.RedLightSecSelBox = QtWidgets.QComboBox(self.frame_23)
        self.RedLightSecSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.RedLightSecSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.RedLightSecSelBox.setObjectName("RedLightSecSelBox")
        self.RedLightSelBox = QtWidgets.QComboBox(self.frame_23)
        self.RedLightSelBox.setGeometry(QtCore.QRect(280, 70, 241, 31))
        self.RedLightSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.RedLightSelBox.setObjectName("RedLightSelBox")
        self.label_834 = QtWidgets.QLabel(self.frame_23)
        self.label_834.setGeometry(QtCore.QRect(20, 130, 151, 41))
        self.label_834.setObjectName("label_834")
        self.MainTabsRed.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.frame_10 = QtWidgets.QFrame(self.tab_11)
        self.frame_10.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_10.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_12.setObjectName("label_12")
        self.GLabelR = QtWidgets.QLabel(self.frame_10)
        self.GLabelR.setGeometry(QtCore.QRect(330, 220, 21, 21))
        self.GLabelR.setObjectName("GLabelR")
        self.FLabelR = QtWidgets.QLabel(self.frame_10)
        self.FLabelR.setGeometry(QtCore.QRect(390, 210, 21, 21))
        self.FLabelR.setObjectName("FLabelR")
        self.ELabelR = QtWidgets.QLabel(self.frame_10)
        self.ELabelR.setGeometry(QtCore.QRect(460, 210, 21, 21))
        self.ELabelR.setObjectName("ELabelR")
        self.ALabelR = QtWidgets.QLabel(self.frame_10)
        self.ALabelR.setGeometry(QtCore.QRect(450, 170, 21, 21))
        self.ALabelR.setObjectName("ALabelR")
        self.BLabelR = QtWidgets.QLabel(self.frame_10)
        self.BLabelR.setGeometry(QtCore.QRect(500, 140, 21, 21))
        self.BLabelR.setObjectName("BLabelR")
        self.CLabelR = QtWidgets.QLabel(self.frame_10)
        self.CLabelR.setGeometry(QtCore.QRect(580, 140, 21, 21))
        self.CLabelR.setObjectName("CLabelR")
        self.DLabelR = QtWidgets.QLabel(self.frame_10)
        self.DLabelR.setGeometry(QtCore.QRect(580, 200, 21, 21))
        self.DLabelR.setObjectName("DLabelR")
        self.TLabelR = QtWidgets.QLabel(self.frame_10)
        self.TLabelR.setGeometry(QtCore.QRect(270, 260, 21, 21))
        self.TLabelR.setObjectName("TLabelR")
        self.SLabelR = QtWidgets.QLabel(self.frame_10)
        self.SLabelR.setGeometry(QtCore.QRect(250, 300, 21, 21))
        self.SLabelR.setObjectName("SLabelR")
        self.RLabelR = QtWidgets.QLabel(self.frame_10)
        self.RLabelR.setGeometry(QtCore.QRect(280, 320, 21, 21))
        self.RLabelR.setObjectName("RLabelR")
        self.QLabelR = QtWidgets.QLabel(self.frame_10)
        self.QLabelR.setGeometry(QtCore.QRect(270, 400, 21, 21))
        self.QLabelR.setObjectName("QLabelR")
        self.PLabelR = QtWidgets.QLabel(self.frame_10)
        self.PLabelR.setGeometry(QtCore.QRect(250, 440, 21, 21))
        self.PLabelR.setObjectName("PLabelR")
        self.HLabelR = QtWidgets.QLabel(self.frame_10)
        self.HLabelR.setGeometry(QtCore.QRect(310, 430, 21, 21))
        self.HLabelR.setObjectName("HLabelR")
        self.OLabelR = QtWidgets.QLabel(self.frame_10)
        self.OLabelR.setGeometry(QtCore.QRect(270, 480, 21, 21))
        self.OLabelR.setObjectName("OLabelR")
        self.ILabelR = QtWidgets.QLabel(self.frame_10)
        self.ILabelR.setGeometry(QtCore.QRect(260, 550, 21, 21))
        self.ILabelR.setObjectName("ILabelR")
        self.NLabelR = QtWidgets.QLabel(self.frame_10)
        self.NLabelR.setGeometry(QtCore.QRect(140, 550, 21, 21))
        self.NLabelR.setObjectName("NLabelR")
        self.JLabelR = QtWidgets.QLabel(self.frame_10)
        self.JLabelR.setGeometry(QtCore.QRect(170, 580, 21, 21))
        self.JLabelR.setObjectName("JLabelR")
        self.KLabelR = QtWidgets.QLabel(self.frame_10)
        self.KLabelR.setGeometry(QtCore.QRect(50, 520, 21, 21))
        self.KLabelR.setObjectName("KLabelR")
        self.MLabelR = QtWidgets.QLabel(self.frame_10)
        self.MLabelR.setGeometry(QtCore.QRect(100, 470, 21, 21))
        self.MLabelR.setObjectName("MLabelR")
        self.LLabelR = QtWidgets.QLabel(self.frame_10)
        self.LLabelR.setGeometry(QtCore.QRect(50, 450, 21, 21))
        self.LLabelR.setObjectName("LLabelR")
        self.frame_24 = QtWidgets.QFrame(self.tab_11)
        self.frame_24.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_24.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.frame_25 = QtWidgets.QFrame(self.tab_11)
        self.frame_25.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_25.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.label_692 = QtWidgets.QLabel(self.frame_25)
        self.label_692.setGeometry(QtCore.QRect(20, 350, 161, 41))
        self.label_692.setObjectName("label_692")
        self.label_690 = QtWidgets.QLabel(self.frame_25)
        self.label_690.setGeometry(QtCore.QRect(280, 20, 201, 41))
        self.label_690.setObjectName("label_690")
        self.RedBlockSelBox = QtWidgets.QComboBox(self.frame_25)
        self.RedBlockSelBox.setGeometry(QtCore.QRect(280, 70, 241, 31))
        self.RedBlockSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.RedBlockSelBox.setObjectName("RedBlockSelBox")
        self.RedSugSpeedLabel = QtWidgets.QLabel(self.frame_25)
        self.RedSugSpeedLabel.setGeometry(QtCore.QRect(270, 200, 111, 41))
        self.RedSugSpeedLabel.setObjectName("RedSugSpeedLabel")
        self.RedFaultTypeLabel = QtWidgets.QLabel(self.frame_25)
        self.RedFaultTypeLabel.setGeometry(QtCore.QRect(180, 420, 301, 41))
        self.RedFaultTypeLabel.setObjectName("RedFaultTypeLabel")
        self.RedAuthLabel = QtWidgets.QLabel(self.frame_25)
        self.RedAuthLabel.setGeometry(QtCore.QRect(170, 270, 191, 41))
        self.RedAuthLabel.setObjectName("RedAuthLabel")
        self.label_686 = QtWidgets.QLabel(self.frame_25)
        self.label_686.setGeometry(QtCore.QRect(20, 270, 141, 41))
        self.label_686.setObjectName("label_686")
        self.label_688 = QtWidgets.QLabel(self.frame_25)
        self.label_688.setGeometry(QtCore.QRect(20, 130, 151, 41))
        self.label_688.setObjectName("label_688")
        self.RedBlockOccLabel = QtWidgets.QLabel(self.frame_25)
        self.RedBlockOccLabel.setGeometry(QtCore.QRect(190, 130, 251, 41))
        self.RedBlockOccLabel.setObjectName("RedBlockOccLabel")
        self.RedFaultStatLabel = QtWidgets.QLabel(self.frame_25)
        self.RedFaultStatLabel.setGeometry(QtCore.QRect(200, 350, 91, 41))
        self.RedFaultStatLabel.setObjectName("RedFaultStatLabel")
        self.label_691 = QtWidgets.QLabel(self.frame_25)
        self.label_691.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_691.setObjectName("label_691")
        self.RedSecSelBox = QtWidgets.QComboBox(self.frame_25)
        self.RedSecSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.RedSecSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.RedSecSelBox.setObjectName("RedSecSelBox")
        self.label_689 = QtWidgets.QLabel(self.frame_25)
        self.label_689.setGeometry(QtCore.QRect(20, 420, 141, 41))
        self.label_689.setObjectName("label_689")
        self.label_687 = QtWidgets.QLabel(self.frame_25)
        self.label_687.setGeometry(QtCore.QRect(20, 200, 231, 41))
        self.label_687.setObjectName("label_687")
        self.frame_24.raise_()
        self.frame_10.raise_()
        self.frame_25.raise_()
        self.MainTabsRed.addTab(self.tab_11, "")
        self.LineTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.MainTabsGrn = QtWidgets.QTabWidget(self.tab_2)
        self.MainTabsGrn.setGeometry(QtCore.QRect(9, 9, 1291, 791))
        self.MainTabsGrn.setObjectName("MainTabsGrn")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.frame_16 = QtWidgets.QFrame(self.tab_16)
        self.frame_16.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_16.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_18 = QtWidgets.QLabel(self.frame_16)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_18.setObjectName("label_18")
        self.PioneerLabel = QtWidgets.QLabel(self.frame_16)
        self.PioneerLabel.setGeometry(QtCore.QRect(330, 80, 61, 21))
        self.PioneerLabel.setObjectName("PioneerLabel")
        self.EdgebrookLabel = QtWidgets.QLabel(self.frame_16)
        self.EdgebrookLabel.setGeometry(QtCore.QRect(410, 30, 71, 21))
        self.EdgebrookLabel.setObjectName("EdgebrookLabel")
        self.StationLabel = QtWidgets.QLabel(self.frame_16)
        self.StationLabel.setGeometry(QtCore.QRect(190, 20, 61, 21))
        self.StationLabel.setObjectName("StationLabel")
        self.WhitedLabel = QtWidgets.QLabel(self.frame_16)
        self.WhitedLabel.setGeometry(QtCore.QRect(130, 120, 61, 21))
        self.WhitedLabel.setObjectName("WhitedLabel")
        self.SouthBankLabel = QtWidgets.QLabel(self.frame_16)
        self.SouthBankLabel.setGeometry(QtCore.QRect(120, 250, 71, 21))
        self.SouthBankLabel.setObjectName("SouthBankLabel")
        self.CentralLabel = QtWidgets.QLabel(self.frame_16)
        self.CentralLabel.setGeometry(QtCore.QRect(200, 330, 61, 21))
        self.CentralLabel.setObjectName("CentralLabel")
        self.InglewoodLabel = QtWidgets.QLabel(self.frame_16)
        self.InglewoodLabel.setGeometry(QtCore.QRect(290, 330, 71, 21))
        self.InglewoodLabel.setObjectName("InglewoodLabel")
        self.GlenburyLabel = QtWidgets.QLabel(self.frame_16)
        self.GlenburyLabel.setGeometry(QtCore.QRect(550, 430, 61, 21))
        self.GlenburyLabel.setObjectName("GlenburyLabel")
        self.DormontLabel = QtWidgets.QLabel(self.frame_16)
        self.DormontLabel.setGeometry(QtCore.QRect(500, 680, 61, 21))
        self.DormontLabel.setObjectName("DormontLabel")
        self.MtLebanonLabel = QtWidgets.QLabel(self.frame_16)
        self.MtLebanonLabel.setGeometry(QtCore.QRect(270, 710, 81, 21))
        self.MtLebanonLabel.setObjectName("MtLebanonLabel")
        self.PoplarLabel = QtWidgets.QLabel(self.frame_16)
        self.PoplarLabel.setGeometry(QtCore.QRect(80, 710, 61, 21))
        self.PoplarLabel.setObjectName("PoplarLabel")
        self.CastleShannonLabel = QtWidgets.QLabel(self.frame_16)
        self.CastleShannonLabel.setGeometry(QtCore.QRect(50, 620, 91, 21))
        self.CastleShannonLabel.setObjectName("CastleShannonLabel")
        self.OverbrookLabel = QtWidgets.QLabel(self.frame_16)
        self.OverbrookLabel.setGeometry(QtCore.QRect(390, 330, 71, 21))
        self.OverbrookLabel.setObjectName("OverbrookLabel")
        self.frame_27 = QtWidgets.QFrame(self.tab_16)
        self.frame_27.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_27.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.GrnStationOccLabel = QtWidgets.QLabel(self.frame_27)
        self.GrnStationOccLabel.setGeometry(QtCore.QRect(190, 130, 251, 41))
        self.GrnStationOccLabel.setObjectName("GrnStationOccLabel")
        self.GrnStationTixLabel = QtWidgets.QLabel(self.frame_27)
        self.GrnStationTixLabel.setGeometry(QtCore.QRect(280, 200, 111, 41))
        self.GrnStationTixLabel.setObjectName("GrnStationTixLabel")
        self.label_842 = QtWidgets.QLabel(self.frame_27)
        self.label_842.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_842.setObjectName("label_842")
        self.label_843 = QtWidgets.QLabel(self.frame_27)
        self.label_843.setGeometry(QtCore.QRect(20, 200, 241, 41))
        self.label_843.setObjectName("label_843")
        self.label_844 = QtWidgets.QLabel(self.frame_27)
        self.label_844.setGeometry(QtCore.QRect(20, 130, 151, 41))
        self.label_844.setObjectName("label_844")
        self.GrnStationSelBox = QtWidgets.QComboBox(self.frame_27)
        self.GrnStationSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.GrnStationSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.GrnStationSelBox.setObjectName("GrnStationSelBox")
        self.frame_26 = QtWidgets.QFrame(self.tab_16)
        self.frame_26.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_26.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.frame_26.raise_()
        self.frame_16.raise_()
        self.frame_27.raise_()
        self.MainTabsGrn.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.frame_17 = QtWidgets.QFrame(self.tab_17)
        self.frame_17.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_17.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_19 = QtWidgets.QLabel(self.frame_17)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_19.setObjectName("label_19")
        self.D_ACLabel = QtWidgets.QLabel(self.frame_17)
        self.D_ACLabel.setGeometry(QtCore.QRect(270, 20, 71, 21))
        self.D_ACLabel.setObjectName("D_ACLabel")
        self.Z_FGLabel = QtWidgets.QLabel(self.frame_17)
        self.Z_FGLabel.setGeometry(QtCore.QRect(110, 200, 81, 21))
        self.Z_FGLabel.setObjectName("Z_FGLabel")
        self.I_JYrdLabel = QtWidgets.QLabel(self.frame_17)
        self.I_JYrdLabel.setGeometry(QtCore.QRect(440, 310, 61, 21))
        self.I_JYrdLabel.setObjectName("I_JYrdLabel")
        self.Yrd_JKLabel = QtWidgets.QLabel(self.frame_17)
        self.Yrd_JKLabel.setGeometry(QtCore.QRect(570, 380, 61, 21))
        self.Yrd_JKLabel.setObjectName("Yrd_JKLabel")
        self.N_MRLabel = QtWidgets.QLabel(self.frame_17)
        self.N_MRLabel.setGeometry(QtCore.QRect(310, 710, 81, 21))
        self.N_MRLabel.setObjectName("N_MRLabel")
        self.N_OQLabel = QtWidgets.QLabel(self.frame_17)
        self.N_OQLabel.setGeometry(QtCore.QRect(160, 710, 91, 21))
        self.N_OQLabel.setObjectName("N_OQLabel")
        self.frame_29 = QtWidgets.QFrame(self.tab_17)
        self.frame_29.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_29.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_841 = QtWidgets.QLabel(self.frame_29)
        self.label_841.setGeometry(QtCore.QRect(20, 130, 211, 41))
        self.label_841.setObjectName("label_841")
        self.GrnSwitchPosLabel = QtWidgets.QLabel(self.frame_29)
        self.GrnSwitchPosLabel.setGeometry(QtCore.QRect(240, 130, 111, 41))
        self.GrnSwitchPosLabel.setObjectName("GrnSwitchPosLabel")
        self.GrnSwitchDirLabel = QtWidgets.QLabel(self.frame_29)
        self.GrnSwitchDirLabel.setGeometry(QtCore.QRect(160, 200, 111, 41))
        self.GrnSwitchDirLabel.setObjectName("GrnSwitchDirLabel")
        self.GrnSwitchSelBox = QtWidgets.QComboBox(self.frame_29)
        self.GrnSwitchSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.GrnSwitchSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.GrnSwitchSelBox.setObjectName("GrnSwitchSelBox")
        self.label_839 = QtWidgets.QLabel(self.frame_29)
        self.label_839.setGeometry(QtCore.QRect(20, 200, 121, 41))
        self.label_839.setObjectName("label_839")
        self.label_840 = QtWidgets.QLabel(self.frame_29)
        self.label_840.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_840.setObjectName("label_840")
        self.frame_28 = QtWidgets.QFrame(self.tab_17)
        self.frame_28.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_28.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.frame_28.raise_()
        self.frame_17.raise_()
        self.frame_29.raise_()
        self.MainTabsGrn.addTab(self.tab_17, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.frame_20 = QtWidgets.QFrame(self.tab_19)
        self.frame_20.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_20.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_22 = QtWidgets.QLabel(self.frame_20)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_22.setObjectName("label_22")
        self.frame_33 = QtWidgets.QFrame(self.tab_19)
        self.frame_33.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_33.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.label_829 = QtWidgets.QLabel(self.frame_33)
        self.label_829.setGeometry(QtCore.QRect(280, 20, 231, 41))
        self.label_829.setObjectName("label_829")
        self.label_845 = QtWidgets.QLabel(self.frame_33)
        self.label_845.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_845.setObjectName("label_845")
        self.GrnLightOccLabel = QtWidgets.QLabel(self.frame_33)
        self.GrnLightOccLabel.setGeometry(QtCore.QRect(190, 130, 111, 41))
        self.GrnLightOccLabel.setObjectName("GrnLightOccLabel")
        self.label_827 = QtWidgets.QLabel(self.frame_33)
        self.label_827.setGeometry(QtCore.QRect(20, 200, 171, 41))
        self.label_827.setObjectName("label_827")
        self.GrnLightStatLabel = QtWidgets.QLabel(self.frame_33)
        self.GrnLightStatLabel.setGeometry(QtCore.QRect(200, 200, 111, 41))
        self.GrnLightStatLabel.setObjectName("GrnLightStatLabel")
        self.GrnLightSecSelBox = QtWidgets.QComboBox(self.frame_33)
        self.GrnLightSecSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.GrnLightSecSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.GrnLightSecSelBox.setObjectName("GrnLightSecSelBox")
        self.GrnLightSelBox = QtWidgets.QComboBox(self.frame_33)
        self.GrnLightSelBox.setGeometry(QtCore.QRect(280, 70, 241, 31))
        self.GrnLightSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.GrnLightSelBox.setObjectName("GrnLightSelBox")
        self.label_828 = QtWidgets.QLabel(self.frame_33)
        self.label_828.setGeometry(QtCore.QRect(20, 130, 151, 41))
        self.label_828.setObjectName("label_828")
        self.frame_32 = QtWidgets.QFrame(self.tab_19)
        self.frame_32.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_32.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.frame_32.raise_()
        self.frame_20.raise_()
        self.frame_33.raise_()
        self.MainTabsGrn.addTab(self.tab_19, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.frame_19 = QtWidgets.QFrame(self.tab_18)
        self.frame_19.setGeometry(QtCore.QRect(600, 0, 691, 771))
        self.frame_19.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_21 = QtWidgets.QLabel(self.frame_19)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 671, 741))
        self.label_21.setObjectName("label_21")
        self.YLabelG = QtWidgets.QLabel(self.frame_19)
        self.YLabelG.setGeometry(QtCore.QRect(80, 280, 21, 21))
        self.YLabelG.setObjectName("YLabelG")
        self.ZLabelG = QtWidgets.QLabel(self.frame_19)
        self.ZLabelG.setGeometry(QtCore.QRect(100, 220, 21, 21))
        self.ZLabelG.setObjectName("ZLabelG")
        self.FLabelG = QtWidgets.QLabel(self.frame_19)
        self.FLabelG.setGeometry(QtCore.QRect(150, 150, 21, 21))
        self.FLabelG.setObjectName("FLabelG")
        self.GLabelG = QtWidgets.QLabel(self.frame_19)
        self.GLabelG.setGeometry(QtCore.QRect(150, 230, 21, 21))
        self.GLabelG.setObjectName("GLabelG")
        self.HLabelG = QtWidgets.QLabel(self.frame_19)
        self.HLabelG.setGeometry(QtCore.QRect(150, 280, 21, 21))
        self.HLabelG.setObjectName("HLabelG")
        self.XLabelG = QtWidgets.QLabel(self.frame_19)
        self.XLabelG.setGeometry(QtCore.QRect(100, 350, 21, 21))
        self.XLabelG.setObjectName("XLabelG")
        self.WLabelG = QtWidgets.QLabel(self.frame_19)
        self.WLabelG.setGeometry(QtCore.QRect(400, 370, 21, 21))
        self.WLabelG.setObjectName("WLabelG")
        self.ILabelG = QtWidgets.QLabel(self.frame_19)
        self.ILabelG.setGeometry(QtCore.QRect(410, 300, 21, 21))
        self.ILabelG.setObjectName("ILabelG")
        self.JLabelG = QtWidgets.QLabel(self.frame_19)
        self.JLabelG.setGeometry(QtCore.QRect(560, 330, 21, 21))
        self.JLabelG.setObjectName("JLabelG")
        self.VLabelG = QtWidgets.QLabel(self.frame_19)
        self.VLabelG.setGeometry(QtCore.QRect(510, 390, 21, 21))
        self.VLabelG.setObjectName("VLabelG")
        self.KLabelG = QtWidgets.QLabel(self.frame_19)
        self.KLabelG.setGeometry(QtCore.QRect(610, 490, 21, 21))
        self.KLabelG.setObjectName("KLabelG")
        self.ULabelG = QtWidgets.QLabel(self.frame_19)
        self.ULabelG.setGeometry(QtCore.QRect(540, 520, 21, 21))
        self.ULabelG.setObjectName("ULabelG")
        self.LLabelG = QtWidgets.QLabel(self.frame_19)
        self.LLabelG.setGeometry(QtCore.QRect(580, 670, 21, 21))
        self.LLabelG.setObjectName("LLabelG")
        self.TLabelG = QtWidgets.QLabel(self.frame_19)
        self.TLabelG.setGeometry(QtCore.QRect(500, 640, 21, 21))
        self.TLabelG.setObjectName("TLabelG")
        self.MLabelG = QtWidgets.QLabel(self.frame_19)
        self.MLabelG.setGeometry(QtCore.QRect(430, 730, 21, 21))
        self.MLabelG.setObjectName("MLabelG")
        self.SLabelG = QtWidgets.QLabel(self.frame_19)
        self.SLabelG.setGeometry(QtCore.QRect(410, 660, 21, 21))
        self.SLabelG.setObjectName("SLabelG")
        self.RLabelG = QtWidgets.QLabel(self.frame_19)
        self.RLabelG.setGeometry(QtCore.QRect(340, 690, 21, 21))
        self.RLabelG.setObjectName("RLabelG")
        self.NLabelG = QtWidgets.QLabel(self.frame_19)
        self.NLabelG.setGeometry(QtCore.QRect(260, 730, 21, 21))
        self.NLabelG.setObjectName("NLabelG")
        self.QLabelG = QtWidgets.QLabel(self.frame_19)
        self.QLabelG.setGeometry(QtCore.QRect(150, 680, 21, 21))
        self.QLabelG.setObjectName("QLabelG")
        self.OLabelG = QtWidgets.QLabel(self.frame_19)
        self.OLabelG.setGeometry(QtCore.QRect(140, 730, 21, 21))
        self.OLabelG.setObjectName("OLabelG")
        self.PLabelG = QtWidgets.QLabel(self.frame_19)
        self.PLabelG.setGeometry(QtCore.QRect(80, 650, 21, 21))
        self.PLabelG.setObjectName("PLabelG")
        self.ELabelG = QtWidgets.QLabel(self.frame_19)
        self.ELabelG.setGeometry(QtCore.QRect(170, 50, 21, 21))
        self.ELabelG.setObjectName("ELabelG")
        self.DLabelG = QtWidgets.QLabel(self.frame_19)
        self.DLabelG.setGeometry(QtCore.QRect(250, 40, 21, 21))
        self.DLabelG.setObjectName("DLabelG")
        self.ALabelG = QtWidgets.QLabel(self.frame_19)
        self.ALabelG.setGeometry(QtCore.QRect(320, 60, 21, 21))
        self.ALabelG.setObjectName("ALabelG")
        self.BLabelG = QtWidgets.QLabel(self.frame_19)
        self.BLabelG.setGeometry(QtCore.QRect(370, 110, 21, 21))
        self.BLabelG.setObjectName("BLabelG")
        self.CLabelG = QtWidgets.QLabel(self.frame_19)
        self.CLabelG.setGeometry(QtCore.QRect(500, 50, 21, 21))
        self.CLabelG.setObjectName("CLabelG")
        self.frame_35 = QtWidgets.QFrame(self.tab_18)
        self.frame_35.setGeometry(QtCore.QRect(20, 10, 561, 741))
        self.frame_35.setStyleSheet("background:rgb(182, 182, 182)")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.frame_34 = QtWidgets.QFrame(self.tab_18)
        self.frame_34.setGeometry(QtCore.QRect(30, 20, 541, 721))
        self.frame_34.setStyleSheet("border-color: rgb(182, 182, 182);")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.label_464 = QtWidgets.QLabel(self.frame_34)
        self.label_464.setGeometry(QtCore.QRect(20, 130, 151, 41))
        self.label_464.setObjectName("label_464")
        self.label_546 = QtWidgets.QLabel(self.frame_34)
        self.label_546.setGeometry(QtCore.QRect(20, 200, 231, 41))
        self.label_546.setObjectName("label_546")
        self.label_547 = QtWidgets.QLabel(self.frame_34)
        self.label_547.setGeometry(QtCore.QRect(20, 270, 141, 41))
        self.label_547.setObjectName("label_547")
        self.GrnSecSelBox = QtWidgets.QComboBox(self.frame_34)
        self.GrnSecSelBox.setGeometry(QtCore.QRect(20, 70, 241, 31))
        self.GrnSecSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.GrnSecSelBox.setObjectName("GrnSecSelBox")
        self.label_465 = QtWidgets.QLabel(self.frame_34)
        self.label_465.setGeometry(QtCore.QRect(280, 20, 201, 41))
        self.label_465.setObjectName("label_465")
        self.label_466 = QtWidgets.QLabel(self.frame_34)
        self.label_466.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.label_466.setObjectName("label_466")
        self.label_548 = QtWidgets.QLabel(self.frame_34)
        self.label_548.setGeometry(QtCore.QRect(20, 350, 161, 41))
        self.label_548.setObjectName("label_548")
        self.label_549 = QtWidgets.QLabel(self.frame_34)
        self.label_549.setGeometry(QtCore.QRect(20, 420, 141, 41))
        self.label_549.setObjectName("label_549")
        self.GrnBlockOccLabel = QtWidgets.QLabel(self.frame_34)
        self.GrnBlockOccLabel.setGeometry(QtCore.QRect(190, 130, 251, 41))
        self.GrnBlockOccLabel.setObjectName("GrnBlockOccLabel")
        self.GrnAuthLabel = QtWidgets.QLabel(self.frame_34)
        self.GrnAuthLabel.setGeometry(QtCore.QRect(170, 270, 191, 41))
        self.GrnAuthLabel.setObjectName("GrnAuthLabel")
        self.GrnSugSpeedLabel = QtWidgets.QLabel(self.frame_34)
        self.GrnSugSpeedLabel.setGeometry(QtCore.QRect(270, 200, 111, 41))
        self.GrnSugSpeedLabel.setObjectName("GrnSugSpeedLabel")
        self.GrnFaultStatLabel = QtWidgets.QLabel(self.frame_34)
        self.GrnFaultStatLabel.setGeometry(QtCore.QRect(200, 350, 91, 41))
        self.GrnFaultStatLabel.setObjectName("GrnFaultStatLabel")
        self.GrnFaultTypeLabel = QtWidgets.QLabel(self.frame_34)
        self.GrnFaultTypeLabel.setGeometry(QtCore.QRect(180, 420, 301, 41))
        self.GrnFaultTypeLabel.setObjectName("GrnFaultTypeLabel")
        self.GrnBlockSelBox = QtWidgets.QComboBox(self.frame_34)
        self.GrnBlockSelBox.setGeometry(QtCore.QRect(280, 70, 241, 31))
        self.GrnBlockSelBox.setStyleSheet("background:rgb(182, 182, 182)")
        self.GrnBlockSelBox.setObjectName("GrnBlockSelBox")
        self.label_547.raise_()
        self.label_546.raise_()
        self.label_464.raise_()
        self.GrnSecSelBox.raise_()
        self.label_465.raise_()
        self.label_466.raise_()
        self.label_548.raise_()
        self.label_549.raise_()
        self.GrnBlockOccLabel.raise_()
        self.GrnAuthLabel.raise_()
        self.GrnSugSpeedLabel.raise_()
        self.GrnFaultStatLabel.raise_()
        self.GrnFaultTypeLabel.raise_()
        self.GrnBlockSelBox.raise_()
        self.MainTabsGrn.addTab(self.tab_18, "")
        self.LineTabWidget.addTab(self.tab_2, "")
        self.CommandEntryLabel = QtWidgets.QTextEdit(self.centralwidget)
        self.CommandEntryLabel.setGeometry(QtCore.QRect(200, 860, 971, 41))
        self.CommandEntryLabel.setStyleSheet("background:rgb(255, 255, 255)")
        self.CommandEntryLabel.setObjectName("CommandEntryLabel")
        self.LoadPLCButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadPLCButton.setGeometry(QtCore.QRect(10, 860, 181, 41))
        self.LogoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutButton.setGeometry(QtCore.QRect(200, 900, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LoadPLCButton.setFont(font)
        self.LoadPLCButton.setStyleSheet("background:rgb(182, 182, 182)")
        self.LoadPLCButton.setObjectName("LoadPLCButton")
        self.LogoutButton.setFont(font)
        self.LogoutButton.setStyleSheet("background:rgb(182, 182, 182)")
        self.LogoutButton.setObjectName("LoadPLCButton")
        self.RunButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(1170, 860, 185, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RunButton.setFont(font)
        self.RunButton.setObjectName("RunButton")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(460, 0, 404, 31))
        self.TimeLabel.setObjectName("TimeLabel")
        self.LoadedPLCLabel = QtWidgets.QLabel(self.centralwidget)
        self.LoadedPLCLabel.setGeometry(QtCore.QRect(870, 0, 481, 31))
        self.LoadedPLCLabel.setObjectName("LoadedPLCLabel")
        self.LoadConfLabel = QtWidgets.QLabel(self.centralwidget)
        self.LoadConfLabel.setGeometry(QtCore.QRect(0,0,0,0))
        self.LoadConfLabel.setObjectName("LoadConfLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.LineTabWidget.setCurrentIndex(0)
        self.MainTabsRed.setCurrentIndex(0)
        self.MainTabsGrn.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Red Line.jpg\"/></p></body></html>"))
        self.ShadysideLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Shadyside</span></p></body></html>"))
        self.HerronLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Herron Ave</span></p></body></html>"))
        self.SwissvilleLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Swissville</span></p></body></html>"))
        self.PennStationLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Penn Station</span></p></body></html>"))
        self.SteelPlazaLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Steel Plaza</span></p></body></html>"))
        self.FirstAveLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">First Ave</span></p></body></html>"))
        self.StationSquareLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Station Square</span></p></body></html>"))
        self.SHJunctionLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">SH Junction</span></p></body></html>"))
        self.label_836.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Total Tickets Sold:</span></p></body></html>"))
        self.label_837.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Station Selection</span></p></body></html>"))
        self.RedStationOccLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.RedStationTixLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxx</span></p></body></html>"))
        self.label_838.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Occupancy:</span></p></body></html>"))
        self.MainTabsRed.setTabText(self.MainTabsRed.indexOf(self.tab_8), _translate("MainWindow", "Stations"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Red Line.jpg\"/></p></body></html>"))
        self.Yrd_CDLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Yard-75</span></p></body></html>"))
        self.F_AELabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">15-16; 1-16</span></p></body></html>"))
        self.T_HLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">27-28; 27-76</span></p></body></html>"))
        self.R_HLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">32-33; 33-72</span></p></body></html>"))
        self.Q_HLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">38-39; 38-71</span></p></body></html>"))
        self.O_HLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">43-44; 44-67</span></p></body></html>"))
        self.I_JNLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">52-53; 52-66</span></p></body></html>"))
        self.label_831.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Switch Selection</span></p></body></html>"))
        self.RedSwitchPosLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxx</span></p></body></html>"))
        self.label_833.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Switch Position:</span></p></body></html>"))
        self.RedSwitchDirLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxx</span></p></body></html>"))
        self.label_835.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Towards:</span></p></body></html>"))
        self.MainTabsRed.setTabText(self.MainTabsRed.indexOf(self.tab_9), _translate("MainWindow", "Switches"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Red Line.jpg\"/></p></body></html>"))
        self.label_830.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Section Selection</span></p></body></html>"))
        self.label_846.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Light Selection</span></p></body></html>"))
        self.RedLightOccLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxx</span></p></body></html>"))
        self.label_832.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Light Status:</span></p></body></html>"))
        self.RedLightStatLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxx</span></p></body></html>"))
        self.label_834.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Occupancy:</span></p></body></html>"))
        self.MainTabsRed.setTabText(self.MainTabsRed.indexOf(self.tab_10), _translate("MainWindow", "Lights"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Red Line.jpg\"/></p></body></html>"))
        self.GLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">G</span></p></body></html>"))
        self.FLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">F</span></p></body></html>"))
        self.ELabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">E</span></p></body></html>"))
        self.ALabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">A</span></p></body></html>"))
        self.BLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">B</span></p></body></html>"))
        self.CLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">C</span></p></body></html>"))
        self.DLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">D</span></p></body></html>"))
        self.TLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">T</span></p></body></html>"))
        self.SLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">S</span></p></body></html>"))
        self.RLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">R</span></p></body></html>"))
        self.QLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Q</span></p></body></html>"))
        self.PLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">P</span></p></body></html>"))
        self.HLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">H</span></p></body></html>"))
        self.OLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">O</span></p></body></html>"))
        self.ILabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">I</span></p></body></html>"))
        self.NLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">N</span></p></body></html>"))
        self.JLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">J</span></p></body></html>"))
        self.KLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">K</span></p></body></html>"))
        self.MLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">M</span></p></body></html>"))
        self.LLabelR.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">L</span></p></body></html>"))
        self.label_692.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Fault Status:</span></p></body></html>"))
        self.label_690.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Block Selection</span></p></body></html>"))
        self.RedSugSpeedLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxx</span></p></body></html>"))
        self.RedFaultTypeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.RedAuthLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxx</span></p></body></html>"))
        self.label_686.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Authority:</span></p></body></html>"))
        self.label_688.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Occupancy:</span></p></body></html>"))
        self.RedBlockOccLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.RedFaultStatLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxx</span></p></body></html>"))
        self.label_691.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Section Selection</span></p></body></html>"))
        self.label_689.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Fault Type:</span></p></body></html>"))
        self.label_687.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Suggested Speed:</span></p></body></html>"))
        self.MainTabsRed.setTabText(self.MainTabsRed.indexOf(self.tab_11), _translate("MainWindow", "Blocks"))
        self.LineTabWidget.setTabText(self.LineTabWidget.indexOf(self.tab), _translate("MainWindow", "Red Line"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Green Line.jpg\"/></p></body></html>"))
        self.PioneerLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Pioneer</span></p></body></html>"))
        self.EdgebrookLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Edgebrook</span></p></body></html>"))
        self.StationLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Station</span></p></body></html>"))
        self.WhitedLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Whited</span></p></body></html>"))
        self.SouthBankLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">South Bank</span></p></body></html>"))
        self.CentralLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Central</span></p></body></html>"))
        self.InglewoodLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Inglewood</span></p></body></html>"))
        self.GlenburyLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Glenbury</span></p></body></html>"))
        self.DormontLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Dormont</span></p></body></html>"))
        self.MtLebanonLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Mt. Lebanon</span></p></body></html>"))
        self.PoplarLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Poplar</span></p></body></html>"))
        self.CastleShannonLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Castle Shannon</span></p></body></html>"))
        self.OverbrookLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Overbrook</span></p></body></html>"))
        self.GrnStationOccLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.GrnStationTixLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxx</span></p></body></html>"))
        self.label_842.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Station Selection</span></p></body></html>"))
        self.label_843.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Total Tickets Sold:</span></p></body></html>"))
        self.label_844.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Occupancy:</span></p></body></html>"))
        self.MainTabsGrn.setTabText(self.MainTabsGrn.indexOf(self.tab_16), _translate("MainWindow", "Stations"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Green Line.jpg\"/></p></body></html>"))
        self.D_ACLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">12-13; 1-13</span></p></body></html>"))
        self.Z_FGLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">29-30; 29-150</span></p></body></html>"))
        self.I_JYrdLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Yard-57</span></p></body></html>"))
        self.Yrd_JKLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Yard-63</span></p></body></html>"))
        self.N_MRLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">76-77; 77-101</span></p></body></html>"))
        self.N_OQLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">85-86; 100-85</span></p></body></html>"))
        self.label_841.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Switch Position:</span></p></body></html>"))
        self.GrnSwitchPosLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxx</span></p></body></html>"))
        self.GrnSwitchDirLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxx</span></p></body></html>"))
        self.label_839.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Towards:</span></p></body></html>"))
        self.label_840.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Switch Selection</span></p></body></html>"))
        self.MainTabsGrn.setTabText(self.MainTabsGrn.indexOf(self.tab_17), _translate("MainWindow", "Switches"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Green Line.jpg\"/></p></body></html>"))
        self.label_829.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Light Selection</span></p></body></html>"))
        self.label_845.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Section Selection</span></p></body></html>"))
        self.GrnLightOccLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxx</span></p></body></html>"))
        self.label_827.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Light Status:</span></p></body></html>"))
        self.GrnLightStatLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxx</span></p></body></html>"))
        self.label_828.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Occupancy:</span></p></body></html>"))
        self.MainTabsGrn.setTabText(self.MainTabsGrn.indexOf(self.tab_19), _translate("MainWindow", "Lights"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Grant/Desktop/Junior_Year/School/Systems_and_Project_Engineering/Iteration_3_Test_File/Green Line.jpg\"/></p></body></html>"))
        self.YLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Y</span></p></body></html>"))
        self.ZLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Z</span></p></body></html>"))
        self.FLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">F</span></p></body></html>"))
        self.GLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">G</span></p></body></html>"))
        self.HLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">H</span></p></body></html>"))
        self.XLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">X</span></p></body></html>"))
        self.WLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">W</span></p></body></html>"))
        self.ILabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">I</span></p></body></html>"))
        self.JLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">J</span></p></body></html>"))
        self.VLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">V</span></p></body></html>"))
        self.KLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">K</span></p></body></html>"))
        self.ULabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">U</span></p></body></html>"))
        self.LLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">L</span></p></body></html>"))
        self.TLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">T</span></p></body></html>"))
        self.MLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">M</span></p></body></html>"))
        self.SLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">S</span></p></body></html>"))
        self.RLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">R</span></p></body></html>"))
        self.NLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">N</span></p></body></html>"))
        self.QLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Q</span></p></body></html>"))
        self.OLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">O</span></p></body></html>"))
        self.PLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">P</span></p></body></html>"))
        self.ELabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">E</span></p></body></html>"))
        self.DLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">D</span></p></body></html>"))
        self.ALabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">A</span></p></body></html>"))
        self.BLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">B</span></p></body></html>"))
        self.CLabelG.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">C</span></p></body></html>"))
        self.label_464.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Occupancy:</span></p></body></html>"))
        self.label_546.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Suggested Speed:</span></p></body></html>"))
        self.label_547.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Authority:</span></p></body></html>"))
        self.label_465.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Block Selection</span></p></body></html>"))
        self.label_466.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Section Selection</span></p></body></html>"))
        self.label_548.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Fault Status:</span></p></body></html>"))
        self.label_549.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; text-decoration: underline;\">Fault Type:</span></p></body></html>"))
        self.GrnBlockOccLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.GrnAuthLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxx</span></p></body></html>"))
        self.GrnSugSpeedLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxx</span></p></body></html>"))
        self.GrnFaultStatLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxx</span></p></body></html>"))
        self.GrnFaultTypeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">xxxxxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.MainTabsGrn.setTabText(self.MainTabsGrn.indexOf(self.tab_18), _translate("MainWindow", "Blocks"))
        self.LineTabWidget.setTabText(self.LineTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Green Line"))
        self.CommandEntryLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.LoadPLCButton.setText(_translate("MainWindow", "Load PLC File"))
        self.LogoutButton.setText(_translate("MainWindow", "Logout"))
        self.RunButton.setText(_translate("MainWindow", "Run Command"))
        self.TimeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time</span></p></body></html>"))
        self.LoadedPLCLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Currently Loaded PLC:</span></p></body></html>"))
        self.LoadConfLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">xxxxxxxxxxxxxxxxxxxx</span></p></body></html>"))
        self.realTime()
        
        
        
    def realTime(self):
        _translate = QtCore.QCoreApplication.translate
        print("Load Your Initial PLC File:")
        global root
        root=tk.Tk()
        root.withdraw()
        file_path = filedialog.askopenfilename()
        self.PLCFile=file_path
        if file_path.partition(".")[2] != "py":
              print("ERROR! Incorrect/Invalid PLC File")
              sys.exit()
        self.LoadedPLCLabel.setText(_translate("MainWindow","Currently Loaded PLC:   "+os.path.basename(file_path)))
        self.LoadedPLCLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
        "font-weight: bold")
        self.LoadedPLCLabel.setAlignment(QtCore.Qt.AlignRight)
        
        self.setupControllers()

        self.LoadPLCButton.clicked.connect(self.clickedLF)
        self.RunButton.clicked.connect(self.clickedCommand)
        #self.LogoutButton.clicked.connect(self.clickedLogout)
       
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.UpdatePLC)
        self.timer.start(50)

    #def clickedLogout(self):
        #sys.exit()

    def clickedCommand(self):
        if self.CommandEntryLabel.toPlainText() == "diagnosticFunction()":
                return
        else:
                print("Command Run Failed: Unknown Function")


    def clickedLF(self):
        root=tk.Tk()
        root.withdraw()
        file_path = filedialog.askopenfilename()
        _translate = QtCore.QCoreApplication.translate
        if file_path.partition(".")[2] != "py":

                self.LoadConfLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">File Load Failed</span></p></body></html>" )) 
                self.LoadConfLabel.setGeometry(QtCore.QRect(10, 900, 181, 21))
                self.LoadConfLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(255, 0, 0);")

                self.LoadedPLCLabel.setText(_translate("MainWindow","Currently Loaded PLC:   "+os.path.basename(file_path)))
                self.LoadedPLCLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                "font-weight: bold")
                self.LoadedPLCLabel.setAlignment(QtCore.Qt.AlignRight)

                QtCore.QTimer.singleShot(3000, self.checkFailPassLabel)
        else:
                self.LoadConfLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">File Load Successful</span></p></body></html>")) 
                self.LoadConfLabel.setGeometry(QtCore.QRect(10, 900, 181, 21))
                self.LoadConfLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
                "background-color: rgb(170, 255, 0);")
                self.PLCFile=file_path
                QtCore.QTimer.singleShot(3000, self.checkFailPassLabel)
                
                
    def checkFailPassLabel(self):
            _translate = QtCore.QCoreApplication.translate
            self.LoadConfLabel.setText(_translate("MainWindow", "")) 
            self.LoadConfLabel.setGeometry(QtCore.QRect(0, 0, 0, 0))

    def UpdatePLC(self):
            _translate = QtCore.QCoreApplication.translate
            self.TimeLabel.setText(_translate("MainWindow", QDate.currentDate().toString(Qt.ISODate)+"   "+QTime.currentTime().toString(Qt.DefaultLocaleLongDate)))
            self.TimeLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
            "font-weight: bold")
            self.TimeLabel.setAlignment(QtCore.Qt.AlignRight)

            #CTC Inputs
            self.routedBlocks=self.CTC.SentRouteBlocks
            self.routedSections=self.CTC.SentRouteSections
            self.routedLines=self.CTC.SentRouteLines
            self.routeSugSpeed=self.CTC.SentSuggestedSpeed
            self.routedAuth=self.CTC.SentSuggestedAuth

            
            self.routedBlockEqual=True
            for i in range(len(self.routedBlocks)):
                if self.prevRoutedBlocks[i]!=self.routedBlocks[i] and len(self.prevRoutedBlocks)!=0:
                    self.routedBlockEqual=False
            
            if self.routedBlockEqual==False:
                for i in range(len(self.routedBlocks)):
                    self.waysideControllers[self.prevRoutedLines[i]][int(self.prevRoutedSections[i],2)].clearRoutedBlocks()
                    self.waysideControllers[self.prevRoutedLines[i]][int(self.prevRoutedSections[i],2)].clearBlockAuthorities()
                    self.waysideControllers[self.prevRoutedLines[i]][int(self.prevRoutedSections[i],2)].clearRoutedSpeeds()

            self.prevRoutedBlocks=list(self.routedBlocks)
            self.prevRoutedSections=list(self.routedSections)
            self.prevRoutedLines=list(self.routedLines)

            #Track Model Inputs
            
            self.redBlocks=self.trackModelDatabase.getRedBlocks()
            self.greenBlocks=self.trackModelDatabase.getGreenBlocks()

            self.greenTicketSales=self.trackModelDatabase.getGreenSales()
            self.redTicketSales=self.trackModelDatabase.getRedSales()

            #input Block Occupancies
            redBlockOcc=[]
            greenBlockOcc=[]
            redTempBlockOcc=[]
            greenTempBlockOcc=[]
            
            for i in range(len(self.redBlocks)):
                redTempBlockOcc.append(self.redBlocks[i].occ)
                if self.redBlocks[i].section=='T':
                    redBlockOcc.append(redTempBlockOcc)
                elif self.redBlocks[i+1].section > self.redBlocks[i].section:
                    redBlockOcc.append(redTempBlockOcc)
                    redTempBlockOcc.clear()

            for i in range(len(self.greenBlocks)):
                greenTempBlockOcc.append(self.greenBlocks[i].occ)
                if self.greenBlocks[i].section=='Z':
                    greenBlockOcc.append(greenTempBlockOcc)
                elif self.greenBlocks[i+1].section > self.greenBlocks[i].section:
                    greenBlockOcc.append(greenTempBlockOcc)
                    greenTempBlockOcc.clear()

            #next block Occs
            self.waysideControllers[1][0].appendBlockOccupancies(self.greenBlocks[12].occ)#A
            self.waysideControllers[1][1].appendBlockOccupancies(self.greenBlocks[2].occ)#B
            self.waysideControllers[1][2].appendBlockOccupancies(self.greenBlocks[5].occ)#C
            self.waysideControllers[1][3].appendBlockOccupancies(self.greenBlocks[16].occ)#D
            self.waysideControllers[1][4].appendBlockOccupancies(self.greenBlocks[20].occ)#E
            self.waysideControllers[1][5].appendBlockOccupancies(self.greenBlocks[29].occ)#F
            self.waysideControllers[1][6].appendBlockOccupancies(self.greenBlocks[32].occ)#G
            self.waysideControllers[1][7].appendBlockOccupancies(self.greenBlocks[35].occ)#H
            self.waysideControllers[1][8].appendBlockOccupancies(self.greenBlocks[57].occ)#I
            self.waysideControllers[1][9].appendBlockOccupancies(self.greenBlocks[62].occ)#J
            self.waysideControllers[1][10].appendBlockOccupancies(self.greenBlocks[68].occ)#K
            self.waysideControllers[1][11].appendBlockOccupancies(self.greenBlocks[73].occ)#L
            self.waysideControllers[1][12].appendBlockOccupancies(self.greenBlocks[76].occ)#M
            self.waysideControllers[1][13].appendBlockOccupancies(self.greenBlocks[85].occ)#N
            self.waysideControllers[1][14].appendBlockOccupancies(self.greenBlocks[88].occ)#O
            self.waysideControllers[1][15].appendBlockOccupancies(self.greenBlocks[97].occ)#P
            self.waysideControllers[1][16].appendBlockOccupancies(self.greenBlocks[84].occ)#Q
            self.waysideControllers[1][17].appendBlockOccupancies(self.greenBlocks[101].occ)#R
            self.waysideControllers[1][18].appendBlockOccupancies(self.greenBlocks[104].occ)#S
            self.waysideControllers[1][19].appendBlockOccupancies(self.greenBlocks[109].occ)#T
            self.waysideControllers[1][20].appendBlockOccupancies(self.greenBlocks[116].occ)#U
            self.waysideControllers[1][21].appendBlockOccupancies(self.greenBlocks[121].occ)#V
            self.waysideControllers[1][22].appendBlockOccupancies(self.greenBlocks[143].occ)#W
            self.waysideControllers[1][23].appendBlockOccupancies(self.greenBlocks[146].occ)#X
            self.waysideControllers[1][24].appendBlockOccupancies(self.greenBlocks[149].occ)#Y
            self.waysideControllers[1][25].appendBlockOccupancies(self.greenBlocks[28].occ)#Z

            #next block faults
            self.waysideControllers[1][0].appendBlockFaults(self.greenBlocks[12].fail)#A
            self.waysideControllers[1][1].appendBlockFaults(self.greenBlocks[2].fail)#B
            self.waysideControllers[1][2].appendBlockFaults(self.greenBlocks[5].fail)#C
            self.waysideControllers[1][3].appendBlockFaults(self.greenBlocks[16].fail)#D
            self.waysideControllers[1][4].appendBlockFaults(self.greenBlocks[20].fail)#E
            self.waysideControllers[1][5].appendBlockFaults(self.greenBlocks[29].fail)#F
            self.waysideControllers[1][6].appendBlockFaults(self.greenBlocks[32].fail)#G
            self.waysideControllers[1][7].appendBlockFaults(self.greenBlocks[35].fail)#H
            self.waysideControllers[1][8].appendBlockFaults(self.greenBlocks[57].fail)#I
            self.waysideControllers[1][9].appendBlockFaults(self.greenBlocks[62].fail)#J
            self.waysideControllers[1][10].appendBlockFaults(self.greenBlocks[68].fail)#K
            self.waysideControllers[1][11].appendBlockFaults(self.greenBlocks[73].fail)#L
            self.waysideControllers[1][12].appendBlockFaults(self.greenBlocks[76].fail)#M
            self.waysideControllers[1][13].appendBlockFaults(self.greenBlocks[85].fail)#N
            self.waysideControllers[1][14].appendBlockFaults(self.greenBlocks[88].fail)#O
            self.waysideControllers[1][15].appendBlockFaults(self.greenBlocks[97].fail)#P
            self.waysideControllers[1][16].appendBlockFaults(self.greenBlocks[84].fail)#Q
            self.waysideControllers[1][17].appendBlockFaults(self.greenBlocks[101].fail)#R
            self.waysideControllers[1][18].appendBlockFaults(self.greenBlocks[104].fail)#S
            self.waysideControllers[1][19].appendBlockFaults(self.greenBlocks[109].fail)#T
            self.waysideControllers[1][20].appendBlockFaults(self.greenBlocks[116].fail)#U
            self.waysideControllers[1][21].appendBlockFaults(self.greenBlocks[121].fail)#V
            self.waysideControllers[1][22].appendBlockFaults(self.greenBlocks[143].fail)#W
            self.waysideControllers[1][23].appendBlockFaults(self.greenBlocks[146].fail)#X
            self.waysideControllers[1][24].appendBlockFaults(self.greenBlocks[149].fail)#Y
            self.waysideControllers[1][25].appendBlockFaults(self.greenBlocks[28].fail)#Z

            for i in range(len(redBlockOcc)):
                self.waysideControllers[0][i].setBlockOccupancies(redBlockOcc[i])
            for i in range(len(greenBlockOcc)):
                self.waysideControllers[1][i].setBlockOccupancies(greenBlockOcc[i])

            #input Underground
            redUnderground=[]
            greenUnderground=[]
            redTempUnderground=[]
            greenTempUnderground=[]
            
            for i in range(len(self.redBlocks)):
                redTempUnderground.append(self.redBlocks[i].under)
                if self.redBlocks[i].section=='T':
                    redUnderground.append(redTempUnderground)
                elif self.redBlocks[i+1].section > self.redBlocks[i].section:
                    redUnderground.append(redTempUnderground)
                    redTempUnderground.clear()

            for i in range(len(self.greenBlocks)):
                greenTempUnderground.append(self.greenBlocks[i].under)
                if self.greenBlocks[i].section=='Z':
                    greenUnderground.append(greenTempUnderground)
                elif self.greenBlocks[i+1].section > self.greenBlocks[i].section:
                    greenUnderground.append(greenTempUnderground)
                    greenTempUnderground.clear()

            for i in range(len(redUnderground)):
                self.waysideControllers[0][i].setUnderground(redUnderground[i])
            for i in range(len(greenUnderground)):
                self.waysideControllers[1][i].setUnderground(greenUnderground[i])

            #input Authority
            for i in range(len(self.routedBlocks)):
                self.waysideControllers[self.routedLines[i]][int(self.routedSections[i],2)].setBlockAuthorities(int(self.routedBlocks[i],2),int(self.routedAuth[i],2))

            #input Fault Statuses
            redFaults=[]
            greenFaults=[]
            redTempFaults=[]
            greenTempFaults=[]
            
            for i in range(len(self.redBlocks)):
                redTempFaults.append(self.redBlocks[i].fail)
                if self.redBlocks[i].section=='T':
                    redFaults.append(redTempFaults)
                elif self.redBlocks[i+1].section > self.redBlocks[i].section:
                    redFaults.append(redTempFaults)
                    redTempFaults.clear()

            for i in range(len(self.greenBlocks)):
                greenTempFaults.append(self.greenBlocks[i].fail)
                if self.greenBlocks[i].section=='Z':
                    greenFaults.append(greenTempFaults)
                elif self.greenBlocks[i+1].section > self.greenBlocks[i].section:
                    greenFaults.append(greenTempFaults)
                    greenTempFaults.clear()

            for i in range(len(redFaults)):
                self.waysideControllers[0][i].setFaultStatuses(redFaults[i])
            for i in range(len(greenFaults)):
                self.waysideControllers[1][i].setFaultStatuses(greenFaults[i])

            #input routed Blocks
            for i in range(len(self.routedBlocks)):
                self.waysideControllers[self.routedLines[i]][int(self.routedSections[i],2)].setRoutedBlocks(int(self.routedBlocks[i],2))
            
            
            for i in range(20):
                contentRed=[]
                contentRed.append("CurrentWaysideLine=Red"+"\n")
                contentRed.append("CurrentWaysideNumber="+str(i)+"\n")
                with open('CurrentWayside.txt','w') as file:
                    file.writelines(contentRed) 
                self.waysideControllers[0][i].runPLC(self.PLCFile)


            for i in range(26):
                contentGreen=[]
                contentGreen.append("CurrentWaysideLine=Green"+"\n")
                contentGreen.append("CurrentWaysideNumber="+str(i)+"\n")
                with open('CurrentWayside.txt','w') as file:
                    file.writelines(contentGreen) 
                self.waysideControllers[1][i].runPLC(self.PLCFile)     

            with open('HWTrackControllerInputs.txt','r') as file:
                HWContent=file.readlines()
            HWContent[2]=str(self.waysideControllers[1][11].getRoutedBlocks())+'\n'
            HWContent[4]=str(self.waysideControllers[1][11].getRoutedAuth())+'\n'
            HWContent[6]=str(self.waysideControllers[1][11].getRoutedSpeeds())+'\n'
            HWContent[8]=str(self.waysideControllers[1][11].getBlockOccupancies())+'\n'
            HWContent[10]=str(self.waysideControllers[1][11].getFaultStatuses())+'\n'
            HWContent[12]=str(self.waysideControllers[1][11].getUnderground())+'\n'

            with open('HWTrackControllerInputs.txt','w') as file:
                file.writelines(HWContent)

    #CTC get functions
    #Get Block Occupancies
    def getRedBlockOcc(self):
        redBlockOcc=[]
        for i in range(len(self.redBlocks)):
            redBlockOcc[i]=self.redBlocks[i].occ
        return redBlockOcc
        
    def getGreenBlockOccpancies(self):
        greenBlockOcc=[]
        for i in range(len(self.greenBlocks)):
            greenBlockOcc[i]=self.greenBlocks[i].occ
        return greenBlockOcc

    #get Ticket Sales
    def getGreenTickets(self):
        return self.greenTicketSales

    def getRedTickets(self):
        return self.redTicketSales

    #get authority

    #get Fault Statuses
    def getGreenFaults(self):
        greenFaults=[]
        for i in range(len(self.greenBlocks)):
            greenFaults[i]=self.greenBlocks[i].fail
        return greenFaults
    
    def getRedFaults(self):
        redFaults=[]
        for i in range(len(self.redBlocks)):
            redFaults[i]=self.redBlocks[i].fail
        return redFaults


    #TrackModel Get Functions
    def getGreenAuth(self):
        greenAuth=[]
        for i in range(len(self.waysideControllers[1])):
            greenAuth=greenAuth+(self.waysideControllers[1][i].getBlockAuth())

        return greenAuth

    def getRedAuth(self):
        redAuth=[]
        for i in range(len(self.waysideControllers[0])):
            redAuth=redAuth+(self.waysideControllers[0][i].getBlockAuth())

        return redAuth

    def getGreenSpeedLimit(self):
        greenSpeed=[]
        for i in range(len(self.waysideControllers[1])):
            greenSpeed=greenSpeed+(self.waysideControllers[1][i].getBlockSugSpeeds())

        return greenSpeed

    def getRedSpeedLimit(self):
        redSpeed=[]
        for i in range(len(self.waysideControllers[0])):
            redSpeed=redSpeed+(self.waysideControllers[0][i].getBlockSugSpeeds())

        return redSpeed
    def getGreenSwitchPos(self):
        greenSW=[]
        greenSW=greenSW+self.waysideControllers[1][3].getSwitchPositions()+self.waysideControllers[1][6].getSwitchPositions()+self.waysideControllers[1][8].getSwitchPositions()+self.waysideControllers[1][10].getSwitchPositions()+self.waysideControllers[1][13].getSwitchPositions()

        return greenSW
    def getRedSwitchPos(self):
        redSW=[]
        redSW=redSW+self.waysideControllers[0][3].getSwitchPositions()+self.waysideControllers[0][5].getSwitchPositions()+self.waysideControllers[0][7].getSwitchPositions()+self.waysideControllers[0][9].getSwitchPositions()

        return redSW

    def getGreenTrainLightSigs(self):
        greenTrainLights=[]
        for i in range(len(self.waysideControllers[1])):
            greenTrainLights=greenTrainLights+(self.waysideControllers[1][i].getTrainLightSignals())

        return greenTrainLights
    def getRedTrainLightSigs(self):
        redTrainLights=[]
        for i in range(len(self.waysideControllers[0])):
            redTrainLights=redTrainLights+(self.waysideControllers[0][i].getTrainLightSignals())

        return redTrainLights

    def getGreenTrafficLights(self):
        greenTrafficLights=[]
        for i in range(len(self.waysideControllers[1])):
            greenTrafficLights=greenTrafficLights+(self.waysideControllers[1][i].getTrafficLightStatus())

        return greenTrafficLights

    def getRedTrafficLights(self):
        redTrafficLights=[]
        for i in range(len(self.waysideControllers[0])):
            redTrafficLights=redTrafficLights+(self.waysideControllers[0][i].getTrafficLightStatus())

        return redTrafficLights

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    #trackApp=QtWidgets.QApplication(sys.argv)
    #trackWindow=QtWidgets.QMainWindow()
    #trackModelDatabase=track()
    #trackModelDatabase.setupUi(trackWindow)
    #trackModelDatabase.importTrack()
    #ui.trackModelInput(trackModelDatabase)
    #window=root
    #CTC=CTCOFFICE(window)
    #ui.CTCInput(CTC)
    #window.mainloop()
    sys.exit(app.exec_())
    
    

