# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainModelupdated.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Train import TrainClass
import MainDisplay
import time


class Ui_MainWindow(object):
        currentTrainDisplay = 1
        def trackModelInstance(self,obj):
                self.trackModel = obj

        def trainControllerInstance(self,obj):
                self.trainController = obj

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(801, 543)
                MainWindow.setDocumentMode(True)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.eBrake = QtWidgets.QPushButton(self.centralwidget)
                self.eBrake.setGeometry(QtCore.QRect(30, 370, 231, 81))
                font = QtGui.QFont()
                font.setPointSize(13)
                font.setBold(True)
                font.setWeight(75)
                self.eBrake.setFont(font)
                self.eBrake.setStyleSheet("background-color: rgb(255, 0, 0);")
                self.eBrake.setObjectName("eBrake")
                self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
                self.groupBox_2.setGeometry(QtCore.QRect(280, 80, 211, 271))
                self.groupBox_2.setObjectName("groupBox_2")
                self.engineFailure = QtWidgets.QPushButton(self.groupBox_2)
                self.engineFailure.setGeometry(QtCore.QRect(10, 20, 191, 41))
                self.engineFailure.setStyleSheet("background-color: rgb(180, 180, 180);")
                self.engineFailure.setObjectName("engineFailure")
                self.signalFailure = QtWidgets.QPushButton(self.groupBox_2)
                self.signalFailure.setGeometry(QtCore.QRect(10, 70, 191, 41))
                self.signalFailure.setStyleSheet("background-color: rgb(180, 180, 180);")
                self.signalFailure.setObjectName("signalFailure")
                self.brakeFailure = QtWidgets.QPushButton(self.groupBox_2)
                self.brakeFailure.setGeometry(QtCore.QRect(10, 120, 191, 41))
                self.brakeFailure.setStyleSheet("background-color: rgb(180, 180, 180);")
                self.brakeFailure.setObjectName("brakeFailure")
                self.failureOutput = QtWidgets.QLabel(self.groupBox_2)
                self.failureOutput.setGeometry(QtCore.QRect(10, 180, 191, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.failureOutput.setFont(font)
                self.failureOutput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "border-color: rgb(195, 0, 0);")
                self.failureOutput.setFrameShape(QtWidgets.QFrame.Box)
                self.failureOutput.setLineWidth(2)
                self.failureOutput.setObjectName("failureOutput")
                self.failureFixed = QtWidgets.QPushButton(self.groupBox_2)
                self.failureFixed.setGeometry(QtCore.QRect(100, 230, 91, 31))
                self.failureFixed.setStyleSheet("background-color: rgb(141, 141, 141);\n"
                "color: rgb(0,0,0);")
                self.failureFixed.setObjectName("failureFixed")
                self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
                self.groupBox.setGeometry(QtCore.QRect(20, 80, 241, 271))
                self.groupBox.setObjectName("groupBox")
                self.currSpeed = QtWidgets.QLCDNumber(self.groupBox)
                self.currSpeed.setGeometry(QtCore.QRect(10, 20, 211, 41))
                self.currSpeed.setObjectName("currSpeed")
                self.speedLimit = QtWidgets.QLCDNumber(self.groupBox)
                self.speedLimit.setGeometry(QtCore.QRect(10, 70, 211, 41))
                self.speedLimit.setObjectName("speedLimit")
                self.commSpeed = QtWidgets.QLCDNumber(self.groupBox)
                self.commSpeed.setGeometry(QtCore.QRect(10, 120, 211, 41))
                self.commSpeed.setObjectName("commSpeed")
                self.accelerationLimit = QtWidgets.QLCDNumber(self.groupBox)
                self.accelerationLimit.setGeometry(QtCore.QRect(10, 170, 211, 41))
                self.accelerationLimit.setObjectName("accelerationLimit")
                self.decelerationLimit = QtWidgets.QLCDNumber(self.groupBox)
                self.decelerationLimit.setGeometry(QtCore.QRect(10, 220, 211, 41))
                self.decelerationLimit.setObjectName("decelerationLimit")
                self.label_2 = QtWidgets.QLabel(self.groupBox)
                self.label_2.setGeometry(QtCore.QRect(20, 20, 81, 41))
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.groupBox)
                self.label_3.setGeometry(QtCore.QRect(20, 80, 71, 21))
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.groupBox)
                self.label_4.setGeometry(QtCore.QRect(20, 122, 71, 41))
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.groupBox)
                self.label_5.setGeometry(QtCore.QRect(20, 170, 71, 41))
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.groupBox)
                self.label_6.setGeometry(QtCore.QRect(20, 222, 91, 41))
                self.label_6.setObjectName("label_6")
                self.label_23 = QtWidgets.QLabel(self.groupBox)
                self.label_23.setGeometry(QtCore.QRect(170, 30, 47, 21))
                self.label_23.setObjectName("label_23")
                self.label_24 = QtWidgets.QLabel(self.groupBox)
                self.label_24.setGeometry(QtCore.QRect(170, 80, 47, 21))
                self.label_24.setObjectName("label_24")
                self.label_25 = QtWidgets.QLabel(self.groupBox)
                self.label_25.setGeometry(QtCore.QRect(170, 130, 47, 21))
                self.label_25.setObjectName("label_25")
                self.label_26 = QtWidgets.QLabel(self.groupBox)
                self.label_26.setGeometry(QtCore.QRect(170, 180, 47, 21))
                self.label_26.setObjectName("label_26")
                self.label_27 = QtWidgets.QLabel(self.groupBox)
                self.label_27.setGeometry(QtCore.QRect(170, 230, 47, 21))
                self.label_27.setObjectName("label_27")
                self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
                self.groupBox_4.setGeometry(QtCore.QRect(280, 360, 211, 141))
                self.groupBox_4.setObjectName("groupBox_4")
                self.label_28 = QtWidgets.QLabel(self.groupBox_4)
                self.label_28.setGeometry(QtCore.QRect(10, 20, 47, 13))
                self.label_28.setObjectName("label_28")
                self.beacon = QtWidgets.QLabel(self.groupBox_4)
                self.beacon.setGeometry(QtCore.QRect(10, 40, 191, 21))
                self.beacon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                "background-color: rgb(243, 0, 0);")
                self.beacon.setFrameShape(QtWidgets.QFrame.Box)
                self.beacon.setObjectName("beacon")
                self.label_30 = QtWidgets.QLabel(self.groupBox_4)
                self.label_30.setGeometry(QtCore.QRect(10, 70, 121, 16))
                self.label_30.setObjectName("label_30")
                self.lineColor = QtWidgets.QLabel(self.groupBox_4)
                self.lineColor.setGeometry(QtCore.QRect(10, 90, 191, 41))
                self.lineColor.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.lineColor.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.lineColor.setFrameShape(QtWidgets.QFrame.Box)
                self.lineColor.setText("")
                self.lineColor.setObjectName("lineColor")
                self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
                self.groupBox_5.setGeometry(QtCore.QRect(510, 360, 261, 141))
                self.groupBox_5.setObjectName("groupBox_5")
                self.label_32 = QtWidgets.QLabel(self.groupBox_5)
                self.label_32.setGeometry(QtCore.QRect(10, 20, 61, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_32.setFont(font)
                self.label_32.setObjectName("label_32")
                self.label_33 = QtWidgets.QLabel(self.groupBox_5)
                self.label_33.setGeometry(QtCore.QRect(10, 40, 51, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_33.setFont(font)
                self.label_33.setObjectName("label_33")
                self.label_34 = QtWidgets.QLabel(self.groupBox_5)
                self.label_34.setGeometry(QtCore.QRect(10, 60, 51, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_34.setFont(font)
                self.label_34.setObjectName("label_34")
                self.label_38 = QtWidgets.QLabel(self.groupBox_5)
                self.label_38.setGeometry(QtCore.QRect(10, 80, 51, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_38.setFont(font)
                self.label_38.setObjectName("label_38")
                self.label_39 = QtWidgets.QLabel(self.groupBox_5)
                self.label_39.setGeometry(QtCore.QRect(10, 100, 51, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_39.setFont(font)
                self.label_39.setObjectName("label_39")
                self.label_40 = QtWidgets.QLabel(self.groupBox_5)
                self.label_40.setGeometry(QtCore.QRect(10, 120, 61, 16))
                font = QtGui.QFont()
                font.setPointSize(9)
                self.label_40.setFont(font)
                self.label_40.setObjectName("label_40")
                self.authorityOutput = QtWidgets.QLabel(self.groupBox_5)
                self.authorityOutput.setGeometry(QtCore.QRect(80, 20, 47, 16))
                self.authorityOutput.setObjectName("authorityOutput")
                self.powerOutput = QtWidgets.QLabel(self.groupBox_5)
                self.powerOutput.setGeometry(QtCore.QRect(80, 40, 47, 16))
                self.powerOutput.setObjectName("powerOutput")
                self.lengthOutput = QtWidgets.QLabel(self.groupBox_5)
                self.lengthOutput.setGeometry(QtCore.QRect(80, 60, 101, 16))
                self.lengthOutput.setObjectName("lengthOutput")
                self.heightOutput = QtWidgets.QLabel(self.groupBox_5)
                self.heightOutput.setGeometry(QtCore.QRect(80, 80, 91, 16))
                self.heightOutput.setObjectName("heightOutput")
                self.widthOutput = QtWidgets.QLabel(self.groupBox_5)
                self.widthOutput.setGeometry(QtCore.QRect(80, 100, 81, 16))
                self.widthOutput.setObjectName("widthOutput")
                self.masOutput = QtWidgets.QLabel(self.groupBox_5)
                self.masOutput.setGeometry(QtCore.QRect(80, 120, 41, 16))
                self.masOutput.setObjectName("masOutput")
                self.authorityOutput_2 = QtWidgets.QLabel(self.groupBox_5)
                self.authorityOutput_2.setGeometry(QtCore.QRect(150, 20, 47, 16))
                self.authorityOutput_2.setObjectName("authorityOutput_2")
                self.powerOutput_2 = QtWidgets.QLabel(self.groupBox_5)
                self.powerOutput_2.setGeometry(QtCore.QRect(150, 40, 47, 16))
                self.powerOutput_2.setObjectName("powerOutput_2")
                self.masOutput_2 = QtWidgets.QLabel(self.groupBox_5)
                self.masOutput_2.setGeometry(QtCore.QRect(150, 120, 41, 16))
                self.masOutput_2.setObjectName("masOutput_2")
                self.trainSelect = QtWidgets.QComboBox(self.centralwidget)
                self.trainSelect.setGeometry(QtCore.QRect(30, 10, 69, 22))
                self.trainSelect.setObjectName("trainSelect")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.trainSelect.addItem("")
                self.CarInfo_9 = QtWidgets.QTabWidget(self.centralwidget)
                self.CarInfo_9.setGeometry(QtCore.QRect(510, 70, 261, 281))
                self.CarInfo_9.setObjectName("CarInfo_9")
                self.Car1_11 = QtWidgets.QWidget()
                self.Car1_11.setObjectName("Car1_11")
                self.passengerCount_11 = QtWidgets.QLCDNumber(self.Car1_11)
                self.passengerCount_11.setGeometry(QtCore.QRect(30, 210, 211, 41))
                self.passengerCount_11.setObjectName("passengerCount_11")
                self.crewCount_11 = QtWidgets.QLCDNumber(self.Car1_11)
                self.crewCount_11.setGeometry(QtCore.QRect(30, 160, 211, 41))
                self.crewCount_11.setObjectName("crewCount_11")
                self.currTemp_1 = QtWidgets.QLCDNumber(self.Car1_11)
                self.currTemp_1.setGeometry(QtCore.QRect(30, 110, 101, 41))
                self.currTemp_1.setObjectName("currTemp_1")
                self.setTemp_1 = QtWidgets.QSpinBox(self.Car1_11)
                self.setTemp_1.setGeometry(QtCore.QRect(190, 110, 51, 41))
                font = QtGui.QFont()
                font.setPointSize(22)
                self.setTemp_1.setFont(font)
                self.setTemp_1.setMinimum(60)
                self.setTemp_1.setProperty("value", 68)
                self.setTemp_1.setObjectName("setTemp_1")
                self.label_280 = QtWidgets.QLabel(self.Car1_11)
                self.label_280.setGeometry(QtCore.QRect(100, 80, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_280.setFont(font)
                self.label_280.setObjectName("label_280")
                self.label_281 = QtWidgets.QLabel(self.Car1_11)
                self.label_281.setGeometry(QtCore.QRect(80, 10, 47, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_281.setFont(font)
                self.label_281.setObjectName("label_281")
                self.label_282 = QtWidgets.QLabel(self.Car1_11)
                self.label_282.setGeometry(QtCore.QRect(20, 30, 111, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_282.setFont(font)
                self.label_282.setObjectName("label_282")
                self.label_283 = QtWidgets.QLabel(self.Car1_11)
                self.label_283.setGeometry(QtCore.QRect(40, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_283.setFont(font)
                self.label_283.setObjectName("label_283")
                self.label_284 = QtWidgets.QLabel(self.Car1_11)
                self.label_284.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.label_284.setObjectName("label_284")
                self.label_285 = QtWidgets.QLabel(self.Car1_11)
                self.label_285.setGeometry(QtCore.QRect(50, 170, 71, 21))
                self.label_285.setObjectName("label_285")
                self.label_286 = QtWidgets.QLabel(self.Car1_11)
                self.label_286.setGeometry(QtCore.QRect(40, 120, 47, 21))
                self.label_286.setObjectName("label_286")
                self.label_287 = QtWidgets.QLabel(self.Car1_11)
                self.label_287.setGeometry(QtCore.QRect(130, 120, 21, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_287.setFont(font)
                self.label_287.setObjectName("label_287")
                self.label_288 = QtWidgets.QLabel(self.Car1_11)
                self.label_288.setGeometry(QtCore.QRect(160, 120, 31, 16))
                self.label_288.setObjectName("label_288")
                self.doors_1 = QtWidgets.QLabel(self.Car1_11)
                self.doors_1.setGeometry(QtCore.QRect(150, 10, 41, 21))
                self.doors_1.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.doors_1.setObjectName("doors_1")
                self.external_1 = QtWidgets.QLabel(self.Car1_11)
                self.external_1.setGeometry(QtCore.QRect(150, 30, 21, 21))
                self.external_1.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.external_1.setObjectName("external_1")
                self.internal_1 = QtWidgets.QLabel(self.Car1_11)
                self.internal_1.setGeometry(QtCore.QRect(150, 50, 31, 21))
                self.internal_1.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.internal_1.setObjectName("internal_1")
                self.CarInfo_9.addTab(self.Car1_11, "")
                self.Car2_11 = QtWidgets.QWidget()
                self.Car2_11.setObjectName("Car2_11")
                self.label_9 = QtWidgets.QLabel(self.Car2_11)
                self.label_9.setGeometry(QtCore.QRect(80, 10, 47, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_9.setFont(font)
                self.label_9.setObjectName("label_9")
                self.doors_2 = QtWidgets.QLabel(self.Car2_11)
                self.doors_2.setGeometry(QtCore.QRect(150, 10, 41, 21))
                self.doors_2.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.doors_2.setObjectName("doors_2")
                self.label_29 = QtWidgets.QLabel(self.Car2_11)
                self.label_29.setGeometry(QtCore.QRect(40, 120, 47, 21))
                self.label_29.setObjectName("label_29")
                self.currTemp_2 = QtWidgets.QLCDNumber(self.Car2_11)
                self.currTemp_2.setGeometry(QtCore.QRect(30, 110, 101, 41))
                self.currTemp_2.setObjectName("currTemp_2")
                self.label_31 = QtWidgets.QLabel(self.Car2_11)
                self.label_31.setGeometry(QtCore.QRect(160, 120, 31, 16))
                self.label_31.setObjectName("label_31")
                self.label_35 = QtWidgets.QLabel(self.Car2_11)
                self.label_35.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.label_35.setObjectName("label_35")
                self.crewCount_2 = QtWidgets.QLCDNumber(self.Car2_11)
                self.crewCount_2.setGeometry(QtCore.QRect(30, 160, 211, 41))
                self.crewCount_2.setObjectName("crewCount_2")
                self.label_14 = QtWidgets.QLabel(self.Car2_11)
                self.label_14.setGeometry(QtCore.QRect(20, 30, 111, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_14.setFont(font)
                self.label_14.setObjectName("label_14")
                self.label_36 = QtWidgets.QLabel(self.Car2_11)
                self.label_36.setGeometry(QtCore.QRect(100, 80, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_36.setFont(font)
                self.label_36.setObjectName("label_36")
                self.setTemp_2 = QtWidgets.QSpinBox(self.Car2_11)
                self.setTemp_2.setGeometry(QtCore.QRect(190, 110, 51, 41))
                font = QtGui.QFont()
                font.setPointSize(22)
                self.setTemp_2.setFont(font)
                self.setTemp_2.setMinimum(60)
                self.setTemp_2.setProperty("value", 68)
                self.setTemp_2.setObjectName("setTemp_2")
                self.passengerCount_2 = QtWidgets.QLCDNumber(self.Car2_11)
                self.passengerCount_2.setGeometry(QtCore.QRect(30, 210, 211, 41))
                self.passengerCount_2.setObjectName("passengerCount_2")
                self.label_37 = QtWidgets.QLabel(self.Car2_11)
                self.label_37.setGeometry(QtCore.QRect(40, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_37.setFont(font)
                self.label_37.setObjectName("label_37")
                self.label_41 = QtWidgets.QLabel(self.Car2_11)
                self.label_41.setGeometry(QtCore.QRect(50, 170, 71, 21))
                self.label_41.setObjectName("label_41")
                self.external_2 = QtWidgets.QLabel(self.Car2_11)
                self.external_2.setGeometry(QtCore.QRect(150, 30, 21, 21))
                self.external_2.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.external_2.setObjectName("external_2")
                self.internal_2 = QtWidgets.QLabel(self.Car2_11)
                self.internal_2.setGeometry(QtCore.QRect(150, 50, 31, 21))
                self.internal_2.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.internal_2.setObjectName("internal_2")
                self.label_42 = QtWidgets.QLabel(self.Car2_11)
                self.label_42.setGeometry(QtCore.QRect(130, 120, 21, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_42.setFont(font)
                self.label_42.setObjectName("label_42")
                self.CarInfo_9.addTab(self.Car2_11, "")
                self.Car3_11 = QtWidgets.QWidget()
                self.Car3_11.setObjectName("Car3_11")
                self.label_10 = QtWidgets.QLabel(self.Car3_11)
                self.label_10.setGeometry(QtCore.QRect(80, 10, 47, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setObjectName("label_10")
                self.doors_3 = QtWidgets.QLabel(self.Car3_11)
                self.doors_3.setGeometry(QtCore.QRect(150, 10, 41, 21))
                self.doors_3.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.doors_3.setObjectName("doors_3")
                self.label_43 = QtWidgets.QLabel(self.Car3_11)
                self.label_43.setGeometry(QtCore.QRect(40, 120, 47, 21))
                self.label_43.setObjectName("label_43")
                self.currTemp_3 = QtWidgets.QLCDNumber(self.Car3_11)
                self.currTemp_3.setGeometry(QtCore.QRect(30, 110, 101, 41))
                self.currTemp_3.setObjectName("currTemp_3")
                self.label_44 = QtWidgets.QLabel(self.Car3_11)
                self.label_44.setGeometry(QtCore.QRect(160, 120, 31, 16))
                self.label_44.setObjectName("label_44")
                self.label_45 = QtWidgets.QLabel(self.Car3_11)
                self.label_45.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.label_45.setObjectName("label_45")
                self.crewCount_4 = QtWidgets.QLCDNumber(self.Car3_11)
                self.crewCount_4.setGeometry(QtCore.QRect(30, 160, 211, 41))
                self.crewCount_4.setObjectName("crewCount_4")
                self.label_15 = QtWidgets.QLabel(self.Car3_11)
                self.label_15.setGeometry(QtCore.QRect(20, 30, 111, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_15.setFont(font)
                self.label_15.setObjectName("label_15")
                self.label_46 = QtWidgets.QLabel(self.Car3_11)
                self.label_46.setGeometry(QtCore.QRect(100, 80, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_46.setFont(font)
                self.label_46.setObjectName("label_46")
                self.setTemp_3 = QtWidgets.QSpinBox(self.Car3_11)
                self.setTemp_3.setGeometry(QtCore.QRect(190, 110, 51, 41))
                font = QtGui.QFont()
                font.setPointSize(22)
                self.setTemp_3.setFont(font)
                self.setTemp_3.setMinimum(60)
                self.setTemp_3.setProperty("value", 68)
                self.setTemp_3.setObjectName("setTemp_3")
                self.passengerCount_4 = QtWidgets.QLCDNumber(self.Car3_11)
                self.passengerCount_4.setGeometry(QtCore.QRect(30, 210, 211, 41))
                self.passengerCount_4.setObjectName("passengerCount_4")
                self.label_47 = QtWidgets.QLabel(self.Car3_11)
                self.label_47.setGeometry(QtCore.QRect(40, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_47.setFont(font)
                self.label_47.setObjectName("label_47")
                self.label_48 = QtWidgets.QLabel(self.Car3_11)
                self.label_48.setGeometry(QtCore.QRect(50, 170, 71, 21))
                self.label_48.setObjectName("label_48")
                self.external_3 = QtWidgets.QLabel(self.Car3_11)
                self.external_3.setGeometry(QtCore.QRect(150, 30, 21, 21))
                self.external_3.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.external_3.setObjectName("external_3")
                self.internal_3 = QtWidgets.QLabel(self.Car3_11)
                self.internal_3.setGeometry(QtCore.QRect(150, 50, 31, 21))
                self.internal_3.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.internal_3.setObjectName("internal_3")
                self.label_49 = QtWidgets.QLabel(self.Car3_11)
                self.label_49.setGeometry(QtCore.QRect(130, 120, 21, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_49.setFont(font)
                self.label_49.setObjectName("label_49")
                self.CarInfo_9.addTab(self.Car3_11, "")
                self.Car4_11 = QtWidgets.QWidget()
                self.Car4_11.setObjectName("Car4_11")
                self.label_11 = QtWidgets.QLabel(self.Car4_11)
                self.label_11.setGeometry(QtCore.QRect(80, 10, 47, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_11.setFont(font)
                self.label_11.setObjectName("label_11")
                self.doors_4 = QtWidgets.QLabel(self.Car4_11)
                self.doors_4.setGeometry(QtCore.QRect(150, 10, 41, 21))
                self.doors_4.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.doors_4.setObjectName("doors_4")
                self.label_50 = QtWidgets.QLabel(self.Car4_11)
                self.label_50.setGeometry(QtCore.QRect(40, 120, 47, 21))
                self.label_50.setObjectName("label_50")
                self.currTemp_4 = QtWidgets.QLCDNumber(self.Car4_11)
                self.currTemp_4.setGeometry(QtCore.QRect(30, 110, 101, 41))
                self.currTemp_4.setObjectName("currTemp_4")
                self.label_51 = QtWidgets.QLabel(self.Car4_11)
                self.label_51.setGeometry(QtCore.QRect(160, 120, 31, 16))
                self.label_51.setObjectName("label_51")
                self.label_52 = QtWidgets.QLabel(self.Car4_11)
                self.label_52.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.label_52.setObjectName("label_52")
                self.crewCount_5 = QtWidgets.QLCDNumber(self.Car4_11)
                self.crewCount_5.setGeometry(QtCore.QRect(30, 160, 211, 41))
                self.crewCount_5.setObjectName("crewCount_5")
                self.label_53 = QtWidgets.QLabel(self.Car4_11)
                self.label_53.setGeometry(QtCore.QRect(20, 30, 111, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_53.setFont(font)
                self.label_53.setObjectName("label_53")
                self.label_54 = QtWidgets.QLabel(self.Car4_11)
                self.label_54.setGeometry(QtCore.QRect(100, 80, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_54.setFont(font)
                self.label_54.setObjectName("label_54")
                self.setTemp_4 = QtWidgets.QSpinBox(self.Car4_11)
                self.setTemp_4.setGeometry(QtCore.QRect(190, 110, 51, 41))
                font = QtGui.QFont()
                font.setPointSize(22)
                self.setTemp_4.setFont(font)
                self.setTemp_4.setMinimum(60)
                self.setTemp_4.setProperty("value", 68)
                self.setTemp_4.setObjectName("setTemp_4")
                self.passengerCount_5 = QtWidgets.QLCDNumber(self.Car4_11)
                self.passengerCount_5.setGeometry(QtCore.QRect(30, 210, 211, 41))
                self.passengerCount_5.setObjectName("passengerCount_5")
                self.label_55 = QtWidgets.QLabel(self.Car4_11)
                self.label_55.setGeometry(QtCore.QRect(40, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_55.setFont(font)
                self.label_55.setObjectName("label_55")
                self.label_83 = QtWidgets.QLabel(self.Car4_11)
                self.label_83.setGeometry(QtCore.QRect(50, 170, 71, 21))
                self.label_83.setObjectName("label_83")
                self.external_4 = QtWidgets.QLabel(self.Car4_11)
                self.external_4.setGeometry(QtCore.QRect(150, 30, 21, 21))
                self.external_4.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.external_4.setObjectName("external_4")
                self.internal_4 = QtWidgets.QLabel(self.Car4_11)
                self.internal_4.setGeometry(QtCore.QRect(150, 50, 31, 21))
                self.internal_4.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.internal_4.setObjectName("internal_4")
                self.label_84 = QtWidgets.QLabel(self.Car4_11)
                self.label_84.setGeometry(QtCore.QRect(130, 120, 21, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_84.setFont(font)
                self.label_84.setObjectName("label_84")
                self.CarInfo_9.addTab(self.Car4_11, "")
                self.Car5_11 = QtWidgets.QWidget()
                self.Car5_11.setObjectName("Car5_11")
                self.label_12 = QtWidgets.QLabel(self.Car5_11)
                self.label_12.setGeometry(QtCore.QRect(80, 10, 47, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_12.setFont(font)
                self.label_12.setObjectName("label_12")
                self.doors_5 = QtWidgets.QLabel(self.Car5_11)
                self.doors_5.setGeometry(QtCore.QRect(150, 10, 41, 21))
                self.doors_5.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.doors_5.setObjectName("doors_5")
                self.label_85 = QtWidgets.QLabel(self.Car5_11)
                self.label_85.setGeometry(QtCore.QRect(40, 120, 47, 21))
                self.label_85.setObjectName("label_85")
                self.currTemp_5 = QtWidgets.QLCDNumber(self.Car5_11)
                self.currTemp_5.setGeometry(QtCore.QRect(30, 110, 101, 41))
                self.currTemp_5.setObjectName("currTemp_5")
                self.label_86 = QtWidgets.QLabel(self.Car5_11)
                self.label_86.setGeometry(QtCore.QRect(160, 120, 31, 16))
                self.label_86.setObjectName("label_86")
                self.label_87 = QtWidgets.QLabel(self.Car5_11)
                self.label_87.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.label_87.setObjectName("label_87")
                self.crewCount_6 = QtWidgets.QLCDNumber(self.Car5_11)
                self.crewCount_6.setGeometry(QtCore.QRect(30, 160, 211, 41))
                self.crewCount_6.setObjectName("crewCount_6")
                self.label_88 = QtWidgets.QLabel(self.Car5_11)
                self.label_88.setGeometry(QtCore.QRect(20, 30, 111, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_88.setFont(font)
                self.label_88.setObjectName("label_88")
                self.label_89 = QtWidgets.QLabel(self.Car5_11)
                self.label_89.setGeometry(QtCore.QRect(100, 80, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_89.setFont(font)
                self.label_89.setObjectName("label_89")
                self.setTemp_5 = QtWidgets.QSpinBox(self.Car5_11)
                self.setTemp_5.setGeometry(QtCore.QRect(190, 110, 51, 41))
                font = QtGui.QFont()
                font.setPointSize(22)
                self.setTemp_5.setFont(font)
                self.setTemp_5.setMinimum(60)
                self.setTemp_5.setProperty("value", 68)
                self.setTemp_5.setObjectName("setTemp_5")
                self.passengerCount_6 = QtWidgets.QLCDNumber(self.Car5_11)
                self.passengerCount_6.setGeometry(QtCore.QRect(30, 210, 211, 41))
                self.passengerCount_6.setObjectName("passengerCount_6")
                self.label_90 = QtWidgets.QLabel(self.Car5_11)
                self.label_90.setGeometry(QtCore.QRect(40, 50, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                font.setWeight(75)
                self.label_90.setFont(font)
                self.label_90.setObjectName("label_90")
                self.label_91 = QtWidgets.QLabel(self.Car5_11)
                self.label_91.setGeometry(QtCore.QRect(50, 170, 71, 21))
                self.label_91.setObjectName("label_91")
                self.external_5 = QtWidgets.QLabel(self.Car5_11)
                self.external_5.setGeometry(QtCore.QRect(150, 30, 21, 21))
                self.external_5.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.external_5.setObjectName("external_5")
                self.internal_5 = QtWidgets.QLabel(self.Car5_11)
                self.internal_5.setGeometry(QtCore.QRect(150, 50, 31, 21))
                self.internal_5.setStyleSheet("background-color: rgb(234, 234, 234);")
                self.internal_5.setObjectName("internal_5")
                self.label_92 = QtWidgets.QLabel(self.Car5_11)
                self.label_92.setGeometry(QtCore.QRect(130, 120, 21, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_92.setFont(font)
                self.label_92.setObjectName("label_92")
                self.CarInfo_9.addTab(self.Car5_11, "")
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                self.CarInfo_9.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.eBrake.setText(_translate("MainWindow", "EMERGENCY BRAKE"))
                self.groupBox_2.setTitle(_translate("MainWindow", "Failure Modes"))
                self.engineFailure.setText(_translate("MainWindow", "Train Engine Failure"))
                self.signalFailure.setText(_translate("MainWindow", "Signal Pickup Failure"))
                self.brakeFailure.setText(_translate("MainWindow", "Brake Failure"))
                self.failureOutput.setText(_translate("MainWindow", "No failures initiated"))
                self.failureFixed.setText(_translate("MainWindow", "Failure Fixed"))
                self.groupBox.setTitle(_translate("MainWindow", "Train Movement"))
                self.label_2.setText(_translate("MainWindow", "Current\nSpeed:"))
                self.label_3.setText(_translate("MainWindow", "Speed Limit:"))
                self.label_4.setText(_translate("MainWindow", "Commanded\nSpeed:"))
                self.label_5.setText(_translate("MainWindow", "Acceleration:"))
                self.label_6.setText(_translate("MainWindow", "Deceleration:"))
                self.label_23.setText(_translate("MainWindow", "MPH"))
                self.label_24.setText(_translate("MainWindow", "MPH"))
                self.label_25.setText(_translate("MainWindow", "MPH"))
                self.label_26.setText(_translate("MainWindow", "m/s^2"))
                self.label_27.setText(_translate("MainWindow", "m/s^2"))
                self.groupBox_4.setTitle(_translate("MainWindow", "Messages"))
                self.label_28.setText(_translate("MainWindow", "Beacon:"))
                self.beacon.setText(_translate("MainWindow", "NOT IN SERVICE"))
                self.label_30.setText(_translate("MainWindow", "Driver Announcements:"))
                self.groupBox_5.setTitle(_translate("MainWindow", "Parameters"))
                self.label_32.setText(_translate("MainWindow", "Authority:"))
                self.label_33.setText(_translate("MainWindow", "Power:"))
                self.label_34.setText(_translate("MainWindow", "Length:"))
                self.label_38.setText(_translate("MainWindow", "Height:"))
                self.label_39.setText(_translate("MainWindow", "Width:"))
                self.label_40.setText(_translate("MainWindow", "Mass:"))
                self.authorityOutput.setText(_translate("MainWindow", "0"))
                self.powerOutput.setText(_translate("MainWindow", "0"))
                self.lengthOutput.setText(_translate("MainWindow", "105.6              feet"))
                self.heightOutput.setText(_translate("MainWindow", "11.2                feet"))
                self.widthOutput.setText(_translate("MainWindow", "8.7                  feet"))
                self.masOutput.setText(_translate("MainWindow", "40.9"))
                self.authorityOutput_2.setText(_translate("MainWindow", "blocks"))
                self.powerOutput_2.setText(_translate("MainWindow", "watts"))
                self.masOutput_2.setText(_translate("MainWindow", "tons"))
                self.trainSelect.setItemText(0, _translate("MainWindow", "Train 1"))
                self.trainSelect.setItemText(1, _translate("MainWindow", "Train 2"))
                self.trainSelect.setItemText(2, _translate("MainWindow", "Train 3"))
                self.trainSelect.setItemText(3, _translate("MainWindow", "Train 4"))
                self.trainSelect.setItemText(4, _translate("MainWindow", "Train 5"))
                self.trainSelect.setItemText(5, _translate("MainWindow", "Train 6"))
                self.trainSelect.setItemText(6, _translate("MainWindow", "Train 7"))
                self.trainSelect.setItemText(7, _translate("MainWindow", "Train 8"))
                self.trainSelect.setItemText(8, _translate("MainWindow", "Train 9"))
                self.trainSelect.setItemText(9, _translate("MainWindow", "Train 10"))
                self.label_280.setText(_translate("MainWindow", "Temperature:"))
                self.label_281.setText(_translate("MainWindow", "Doors:"))
                self.label_282.setText(_translate("MainWindow", " Internal Lights:"))
                self.label_283.setText(_translate("MainWindow", "  Headlights:"))
                self.label_284.setText(_translate("MainWindow", "Passenger count:"))
                self.label_285.setText(_translate("MainWindow", "Crew count:"))
                self.label_286.setText(_translate("MainWindow", "Current:"))
                self.label_287.setText(_translate("MainWindow", " \N{DEGREE SIGN}F"))
                self.label_288.setText(_translate("MainWindow", "Set:"))
                self.doors_1.setText(_translate("MainWindow", "Closed"))
                self.external_1.setText(_translate("MainWindow", "Off"))
                self.internal_1.setText(_translate("MainWindow", "Off"))
                self.CarInfo_9.setTabText(self.CarInfo_9.indexOf(self.Car1_11), _translate("MainWindow", "Car 1"))
                self.label_9.setText(_translate("MainWindow", "Doors:"))
                self.doors_2.setText(_translate("MainWindow", "Closed"))
                self.label_29.setText(_translate("MainWindow", "Current:"))
                self.label_31.setText(_translate("MainWindow", "Set:"))
                self.label_35.setText(_translate("MainWindow", "Passenger count:"))
                self.label_14.setText(_translate("MainWindow", " Internal Lights:"))
                self.label_36.setText(_translate("MainWindow", "Temperature:"))
                self.label_37.setText(_translate("MainWindow", "  Headlights:"))
                self.label_41.setText(_translate("MainWindow", "Crew count:"))
                self.external_2.setText(_translate("MainWindow", "Off"))
                self.internal_2.setText(_translate("MainWindow", "Off"))
                self.label_42.setText(_translate("MainWindow", " \N{DEGREE SIGN}F"))
                self.CarInfo_9.setTabText(self.CarInfo_9.indexOf(self.Car2_11), _translate("MainWindow", "Car 2"))
                self.label_10.setText(_translate("MainWindow", "Doors:"))
                self.doors_3.setText(_translate("MainWindow", "Closed"))
                self.label_43.setText(_translate("MainWindow", "Current:"))
                self.label_44.setText(_translate("MainWindow", "Set:"))
                self.label_45.setText(_translate("MainWindow", "Passenger count:"))
                self.label_15.setText(_translate("MainWindow", " Internal Lights:"))
                self.label_46.setText(_translate("MainWindow", "Temperature:"))
                self.label_47.setText(_translate("MainWindow", "  Headlights:"))
                self.label_48.setText(_translate("MainWindow", "Crew count:"))
                self.external_3.setText(_translate("MainWindow", "Off"))
                self.internal_3.setText(_translate("MainWindow", "Off"))
                self.label_49.setText(_translate("MainWindow", " \N{DEGREE SIGN}F"))
                self.CarInfo_9.setTabText(self.CarInfo_9.indexOf(self.Car3_11), _translate("MainWindow", "Car 3"))
                self.label_11.setText(_translate("MainWindow", "Doors:"))
                self.doors_4.setText(_translate("MainWindow", "Closed"))
                self.label_50.setText(_translate("MainWindow", "Current:"))
                self.label_51.setText(_translate("MainWindow", "Set:"))
                self.label_52.setText(_translate("MainWindow", "Passenger count:"))
                self.label_53.setText(_translate("MainWindow", " Internal Lights:"))
                self.label_54.setText(_translate("MainWindow", "Temperature:"))
                self.label_55.setText(_translate("MainWindow", "  Headlights:"))
                self.label_83.setText(_translate("MainWindow", "Crew count:"))
                self.external_4.setText(_translate("MainWindow", "Off"))
                self.internal_4.setText(_translate("MainWindow", "Off"))
                self.label_84.setText(_translate("MainWindow", " \N{DEGREE SIGN}F"))
                self.CarInfo_9.setTabText(self.CarInfo_9.indexOf(self.Car4_11), _translate("MainWindow", "Car 4"))
                self.label_12.setText(_translate("MainWindow", "Doors:"))
                self.doors_5.setText(_translate("MainWindow", "Closed"))
                self.label_85.setText(_translate("MainWindow", "Current:"))
                self.label_86.setText(_translate("MainWindow", "Set:"))
                self.label_87.setText(_translate("MainWindow", "Passenger count:"))
                self.label_88.setText(_translate("MainWindow", " Internal Lights:"))
                self.label_89.setText(_translate("MainWindow", "Temperature:"))
                self.label_90.setText(_translate("MainWindow", "  Headlights:"))
                self.label_91.setText(_translate("MainWindow", "Crew count:"))
                self.external_5.setText(_translate("MainWindow", "Off"))
                self.internal_5.setText(_translate("MainWindow", "Off"))
                self.label_92.setText(_translate("MainWindow", " \N{DEGREE SIGN}F"))
                self.CarInfo_9.setTabText(self.CarInfo_9.indexOf(self.Car5_11), _translate("MainWindow", "Car 5"))

                #creating ten train class instances
                self.trains = []
                self.trains.append(TrainClass(0))
                self.trains.append(TrainClass(1))
                self.trains.append(TrainClass(2))
                self.trains.append(TrainClass(3))
                self.trains.append(TrainClass(4))
                self.trains.append(TrainClass(5))
                self.trains.append(TrainClass(6))
                self.trains.append(TrainClass(7))
                self.trains.append(TrainClass(8))
                self.trains.append(TrainClass(9))

                

                #creating arrays for lights, doors
                self.externalLights = [self.internal_1,self.internal_2,self.internal_3,self.internal_4,self.internal_5]
                self.cabinLights = [self.external_1,self.external_2,self.external_3,self.external_4,self.external_5]
                self.doors = [self.doors_1,self.doors_2,self.doors_3,self.doors_4,self.doors_5]
                self.setTemps = [self.setTemp_1,self.setTemp_2,self.setTemp_3,self.setTemp_4,self.setTemp_5]
                self.currTemps = [self.currTemp_1,self.currTemp_2,self.currTemp_3,self.currTemp_4,self.currTemp_5]

                self.timer = QtCore.QTimer()
                self.timer.timeout.connect(self.updateEverything)
                self.timer.start(100)
                
                self.currentTrainDisplay = self.trainSelect.currentIndex()

                # button events and where to go
                self.trainSelect.currentIndexChanged.connect(self.TrainWindow)
                self.eBrake.clicked.connect(lambda: self.eBrakePressed(0))
                self.setTemp_1.valueChanged.connect(lambda: self.changeTemp(self.currentTrainDisplay,0))
                self.setTemp_2.valueChanged.connect(lambda: self.changeTemp(self.currentTrainDisplay,1))
                self.setTemp_3.valueChanged.connect(lambda: self.changeTemp(self.currentTrainDisplay,2))
                self.setTemp_4.valueChanged.connect(lambda: self.changeTemp(self.currentTrainDisplay,3))
                self.setTemp_5.valueChanged.connect(lambda: self.changeTemp(self.currentTrainDisplay,4))
                self.engineFailure.clicked.connect(self.eFail)
                self.signalFailure.clicked.connect(self.sFail)
                self.brakeFailure.clicked.connect(self.bFail)
                self.failureFixed.clicked.connect(self.failFix)

        def TrainWindow(self):
                self.currentTrainDisplay = self.trainSelect.currentIndex() # indexed at 0 
                self.updateTrainDisplay(self.currentTrainDisplay)

        def updateTrainDisplay(self,trainNum):
                self.currSpeed.display(round(self.trains[trainNum].velocityMPH,1))
                self.speedLimit.display(round(self.trains[trainNum].speed_limit,1))
                self.commSpeed.display(round((self.trains[trainNum].commSpeed / 1.609),1))
                if (self.trains[trainNum].acceleration > 0):
                        self.accelerationLimit.display(round(self.trains[trainNum].acceleration,1))
                        self.decelerationLimit.display(0)
                elif (self.trains[trainNum].acceleration < 0):
                        self.accelerationLimit.display(0)
                        self.decelerationLimit.display(abs(round(self.trains[trainNum].acceleration,1)))
                else:
                        self.accelerationLimit.display(0)
                        self.decelerationLimit.display(0)
                
                self.beacon.setText(self.trains[trainNum].beacon)
                self.beacon.setStyleSheet("background-color: rgb(255,255,255)")
                self.authorityOutput.setText(str(self.trains[trainNum].authority))
                self.powerOutput.setText(str(self.trains[trainNum].power))
                self.masOutput.setText(str(self.trains[trainNum].massTon))
                self.lineColor.setText(self.trains[trainNum].announcement)

                #update door and light status status
                for x in range(5):
                        if self.trains[trainNum].doorStatus == False:
                                self.doors[x].setText("Closed")
                                self.doors[x].setStyleSheet("background-color: rgb(234, 234, 234)")
                        else:
                                self.doors[x].setText("Open")
                                self.doors[x].setStyleSheet("background-color: rgb(57, 255, 35)")
                        
                        if self.trains[trainNum].internalStatus == False:
                                self.cabinLights[x].setText("Off")
                                self.cabinLights[x].setStyleSheet("background-color: rgb(234, 234, 234)")
                        else:
                                self.cabinLights[x].setText("On")
                                self.cabinLights[x].setStyleSheet("background-color: rgb(57, 255, 35)")

                        if self.trains[trainNum].externalStatus == False and self.trains[trainNum].externalStatusTrack == 0:
                                self.externalLights[x].setText("Off")
                                self.externalLights[x].setStyleSheet("background-color: rgb(234, 234, 234)")
                        elif self.trains[trainNum].externalStatus == True: # or self.trains[trainNum].externalStatusTrack == True:
                                self.externalLights[x].setText("On")
                                self.externalLights[x].setStyleSheet("background-color: rgb(57, 255, 35)")

                #setCurrentTemps
                self.currTemp_1.display(self.trains[trainNum].temperature)
                self.currTemp_2.display(self.trains[trainNum].temperature)
                self.currTemp_3.display(self.trains[trainNum].temperature)
                self.currTemp_4.display(self.trains[trainNum].temperature)
                self.currTemp_5.display(self.trains[trainNum].temperature)

                #set passenger count
                self.passengerCount_11.display(self.trains[trainNum].passenger)
                self.passengerCount_2.display(self.trains[trainNum].passenger)
                self.passengerCount_4.display(self.trains[trainNum].passenger)
                self.passengerCount_5.display(self.trains[trainNum].passenger)
                self.passengerCount_6.display(self.trains[trainNum].passenger)

                #set crew count
                self.crewCount_11.display(self.trains[trainNum].crew)
                self.crewCount_2.display(self.trains[trainNum].crew)
                self.crewCount_4.display(self.trains[trainNum].crew)
                self.crewCount_5.display(self.trains[trainNum].crew)
                self.crewCount_6.display(self.trains[trainNum].crew)

        def updateEverything(self):
                for i in range(len(self.trains)): 
                        self.getValuesFromTrackModel(i)
                        self.getValuesFromTrainController(i)

                self.updateTrainDisplay(self.currentTrainDisplay)
                        
        def eBrakePressed(self,whichOne):
                if whichOne == 0:
                        if self.trains[self.currentTrainDisplay].emergencyPass == 0:
                                self.trains[self.currentTrainDisplay].emergencyPass = 1
                        else:
                               self.trains[self.currentTrainDisplay].emergencyPass = 0
                               self.trains[self.currentTrainDisplay].brakesDone() 
                elif whichOne == 1:
                        self.trains[self.currentTrainDisplay].emergency = 1
                elif whichOne == 2:
                        self.trains[self.currentTrainDisplay].emergencyFail = 1
                self.trains[self.currentTrainDisplay].eBrakePressed(whichOne)
                self.updateEverything()

        def changeTemp(self,trainID,carNum):
                self.trains[trainID].temperature = self.setTemps[carNum].value()
                for x in range(5):
                        self.currTemps[x].display(self.trains[trainID].temperature)

        def eFail(self):
                self.trains[self.currentTrainDisplay].engineFailure = True
                self.trains[self.currentTrainDisplay].faults = 1

                self.failureOutput.setText("Engine Failure")
                self.engineFailure.setStyleSheet("background-color: rgb(255, 0, 0);")
                self.eBrakePressed(2)

        def sFail(self):
                self.trains[self.currentTrainDisplay].signalFailure = True
                self.trains[self.currentTrainDisplay].faults = 2

                self.trains[self.currentTrainDisplay].authority = 0

                self.failureOutput.setText("Signal Pickup Failure")
                self.signalFailure.setStyleSheet("background-color: rgb(255, 0, 0);")
                self.eBrakePressed(2)

        def bFail(self):
                self.trains[self.currentTrainDisplay].brakeFailure = True
                self.trains[self.currentTrainDisplay].faults = 3

                #causes brakes not to work
                

                self.failureOutput.setText("Brake Failure")
                self.brakeFailure.setStyleSheet("background-color: rgb(255, 0, 0);")

        def failFix(self):
                self.trains[self.currentTrainDisplay].engineFailure = False
                self.trains[self.currentTrainDisplay].signalFailure = False
                self.trains[self.currentTrainDisplay].brakeFailure = False
                self.trains[self.currentTrainDisplay].faults = 0
                self.engineFailure.setStyleSheet("background-color: rgb(234,234,234);")
                self.signalFailure.setStyleSheet("background-color: rgb(234,234,234);")
                self.brakeFailure.setStyleSheet("background-color: rgb(234,234,234);")
                self.failureOutput.setText("No failures")
                self.trains[self.currentTrainDisplay].brakesDone()
                self.updateEverything()


        ################ train controller functions ###################
        def getVelocity(self,trainID):
                return self.trains[trainID].velocityKM

        def getSpeedLimit(self,trainID):
                return self.trains[trainID].speed_limit

        def getCommanded(self,trainID):
                return self.trains[trainID].commSpeed

        def getAuthority(self,trainID):
                return self.trains[trainID].authority

        def getBeacon(self,trainID):
                return self.trains[trainID].beacon

        def getTrainFaults(self,trainID):
                return self.trains[trainID].faults

        def getDispatched(self):
                return [self.trains[0].dispatched,self.trains[1].dispatched,self.trains[2].dispatched,self.trains[3].dispatched,self.trains[4].dispatched,self.trains[5].dispatched,self.trains[6].dispatched,self.trains[7].dispatched,self.trains[8].dispatched,self.trains[9].dispatched]

        def getValuesFromTrainController(self,trainID):
                emerTemp = self.trains[trainID].emergency
                serviceTemp = self.trains[trainID].service

                if self.trains[trainID].velocity == 0 and self.trains[trainID].service == 1:
                        self.trains[trainID].power = 0
                else:
                        self.trains[trainID].power = self.trainController.getPower(trainID)
                #check power
                if self.trains[trainID].power > 120000:
                        self.trains[trainID].power = 120000
                elif self.trains[trainID].power < -120000:
                        self.trains[trainID].power = -120000

                self.trains[trainID].externalStatus = self.trainController.getHeadlightStatus(trainID)
                self.trains[trainID].internalStatus = self.trainController.getCabinLightStatus(trainID)
                self.trains[trainID].doorStatus = self.trainController.getDoorStatus(trainID)
                self.trains[trainID].emergency = self.trainController.getEBrake(trainID)
                self.trains[trainID].service = self.trainController.getServiceBrake(trainID)
                
                self.trains[trainID].announcement = self.trainController.getAnnouncement(trainID)
                self.trains[trainID].set_speed = self.trainController.getSetSpeed(trainID)

                if (self.trains[trainID].doorStatus == 1):
                        self.trains[trainID].openDoors()

                if self.trains[trainID].brakeFailure == 1 and self.trains[trainID].service == 1:
                        self.trains[trainID].brakesDone()

                if self.trains[trainID].emergencyPass == 1:
                        pass
                elif self.trains[trainID].emergency != emerTemp and self.trains[trainID].emergency == 1:
                        self.trains[trainID].eBrakePressed(1)
                elif (self.trains[trainID].service != serviceTemp) and (self.trains[trainID].service == 0):
                        self.trains[trainID].brakesDone()
                elif (self.trains[trainID].service != serviceTemp) and (self.trains[trainID].service == 1) and (self.trains[trainID].emergency != 1):
                        self.trains[trainID].serviceBrake()

                self.trains[trainID].calculateVelocity()

        ################ track model functions ##################
        def getValuesFromTrackModel(self,trainID):
                tempAuth = self.trains[trainID].authority
                self.trains[trainID].authority = int(self.trackModel.getAuth(self.trains[trainID].line,self.trains[trainID].blockNum))
                self.trains[trainID].commSpeed, self.trains[trainID].speed_limit = self.trackModel.getSpeed(self.trains[trainID].line,self.trains[trainID].blockNum)
                tempBeacon = self.trackModel.getBeacon(self.trains[trainID].line,self.trains[trainID].blockNum)
                if(tempBeacon!="None"):
                        self.trains[trainID].beacon=tempBeacon 
                self.trains[trainID].externalStatusTrack = self.trackModel.getLight(self.trains[trainID].line,self.trains[trainID].blockNum)
                self.trains[trainID].stationDoors = self.trackModel.getStationSide(self.trains[trainID].line,self.trains[trainID].blockNum)
                self.trains[trainID].openDoors()
                self.trains[trainID].blockGrade, self.trains[trainID].elevation, self.trains[trainID].cElevation, self.trains[trainID].blockLength = self.trackModel.getBlockGrade(self.trains[trainID].line,self.trains[trainID].blockNum)
                self.trains[trainID].boarding = self.trackModel.getBoarding(self.trains[trainID].line,self.trains[trainID].blockNum)
                self.trains[trainID].calculatePassengers()
                self.trains[trainID].base, self.trains[trainID].switchBlock = self.trackModel.getSwitch(self.trains[trainID].line,self.trains[trainID].blockNum)
                self.trains[trainID].signal = self.trackModel.getSwitch(self.trains[trainID].line,self.trains[trainID].blockNum)

                self.trains[trainID].switches()

                self.trackModel.setTrainPos(self.trains[trainID].ID,self.trains[trainID].line,self.trains[trainID].blockNum)
                self.trackModel.setTrainFault(trainID, self.trains[trainID].faults)

                if self.trains[trainID].signalFailure == True:
                        self.trains[trainID].authority = 0
                        self.trainController.serviceBrakeControl()
                elif int(self.trains[trainID].authority) <= 0 and tempAuth != 0:
                        if trainID == 0:
                                self.trainController.serviceBrakeControl()
                        elif trainID == 1:
                                self.trainController.serviceBrakeControl1()
                        elif trainID == 2:
                                self.trainController.serviceBrakeControl2()
                        elif trainID == 3:
                                self.trainController.serviceBrakeControl3()
                        elif trainID == 4:
                                self.trainController.serviceBrakeControl4()
                        elif trainID == 5:
                                self.trainController.serviceBrakeControl5()
                        elif trainID == 6:
                                self.trainController.serviceBrakeControl6()
                        elif trainID == 7:
                                self.trainController.serviceBrakeControl7()
                        elif trainID == 8:
                                self.trainController.serviceBrakeControl8()
                        elif trainID == 9:
                                self.trainController.serviceBrakeControl9()
                elif int(self.trains[trainID].authority) > 0 and int(tempAuth) < 1:
                        self.trains[trainID].brakesDone()
                        """print("authority more than zero after zero")
                        if trainID == 0:
                                self.trainController.serviceBrakeControl()
                        elif trainID == 1:
                                self.trainController.serviceBrakeControl1()
                        elif trainID == 2:
                                self.trainController.serviceBrakeControl2()
                        elif trainID == 3:
                                self.trainController.serviceBrakeControl3()
                        elif trainID == 4:
                                self.trainController.serviceBrakeControl4()
                        elif trainID == 5:
                                self.trainController.serviceBrakeControl5()
                        elif trainID == 6:
                                self.trainController.serviceBrakeControl6()
                        elif trainID == 7:
                                self.trainController.serviceBrakeControl7()
                        elif trainID == 8:
                                self.trainController.serviceBrakeControl8()
                        elif trainID == 9:
                                self.trainController.serviceBrakeControl9() """

        # when a train is dispatch
        def dispatched(self,trainID,temp):

                self.trains[trainID].dispatched = True

                if temp == "Green":
                        self.trains[trainID].line = 1
                        self.trains[trainID].setLine(1)
                        self.trains[trainID].blockNum = 63
                else:
                        self.trains[trainID].line = 0
                        self.trains[trainID].setLine(0)
                        self.trains[trainID].blockNum = 9

                #since dispatched, take off emergency brakes
                self.trains[trainID].brakesDone()
                self.getValuesFromTrackModel(trainID)


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())